import type { VocabularyLevel, WordFamily } from '../types';

type SeedRow = {
  word: string;
  level: VocabularyLevel;
  category: string;
  chinese: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  word_family: WordFamily;
  collocations: string[];
  example_sentence: string;
  edutest_frequency: number;
  writing_value: string;
};

export const L5: SeedRow[] = [
  { word: 'ambiguous', level: 5, category: 'Academic', chinese: '模棱两可的', definition: 'Having more than one possible meaning; unclear.', synonyms: ['unclear', 'equivocal'], antonyms: ['unambiguous', 'explicit'], word_family: { noun: 'ambiguity', adverb: 'ambiguously' }, collocations: ['ambiguous ending', 'ambiguous remark'], example_sentence: 'An ambiguous ending is not a failed ending if the uncertainty is the point.', edutest_frequency: 5, writing_value: 'High-level reading word.' },
  { word: 'ambivalent', level: 5, category: 'Emotion', chinese: '矛盾的', definition: 'Having mixed or opposing feelings about something.', synonyms: ['conflicted', 'undecided'], antonyms: ['certain', 'decisive'], word_family: { noun: 'ambivalence' }, collocations: ['ambivalent about', 'ambivalent attitude'], example_sentence: 'He felt ambivalent about winning if it meant a friend went home disappointed.', edutest_frequency: 4, writing_value: 'Complex emotion.' },
  { word: 'analogous', level: 5, category: 'Academic', chinese: '类似的', definition: 'Comparable in a way that helps explanation.', synonyms: ['comparable', 'similar'], antonyms: ['unlike', 'dissimilar'], word_family: { noun: 'analogy' }, collocations: ['analogous to', 'analogous situation'], example_sentence: 'The trapped animal is analogous to the character’s fear, not a random extra scene.', edutest_frequency: 4, writing_value: 'Comparison at a high level.' },
  { word: 'arbitrary', level: 5, category: 'Academic', chinese: '任意的', definition: 'Based on personal choice or chance rather than reason or a system.', synonyms: ['random', 'capricious'], antonyms: ['reasoned', 'systematic'], word_family: { noun: 'arbitrariness', adverb: 'arbitrarily' }, collocations: ['arbitrary rule', 'arbitrary decision'], example_sentence: 'An arbitrary rule invites rebellion; a explained rule invites debate.', edutest_frequency: 4, writing_value: 'Fairness and logic.' },
  { word: 'articulate', level: 5, category: 'Communication', chinese: '表达清晰的', definition: 'Able to express ideas clearly; to express an idea clearly.', synonyms: ['eloquent', 'expressive'], antonyms: ['inarticulate', 'tongue-tied'], word_family: { noun: 'articulation', adverb: 'articulately' }, collocations: ['articulate a view', 'articulate speaker'], example_sentence: 'He could not yet articulate why the ending felt unfair, but he could point to the broken promise.', edutest_frequency: 4, writing_value: 'Speech and writing praise.' },
  { word: 'ascertain', level: 5, category: 'Academic', chinese: '查明', definition: 'To find something out for certain.', synonyms: ['determine', 'establish'], antonyms: ['guess'], word_family: {}, collocations: ['ascertain the facts', 'ascertain whether'], example_sentence: 'Ascertain what the question actually asks before you start the heroic paragraph.', edutest_frequency: 3, writing_value: 'Formal investigation verb.' },
  { word: 'assert', level: 5, category: 'Academic', chinese: '断言', definition: 'To state a claim firmly.', synonyms: ['declare', 'maintain'], antonyms: ['deny', 'withdraw'], word_family: { noun: 'assertion', adjective: 'assertive' }, collocations: ['assert a claim', 'assert that'], example_sentence: 'Anyone can assert a claim; the marks go to the student who supports it.', edutest_frequency: 4, writing_value: 'Argument verb.' },
  { word: 'attain', level: 5, category: 'Academic', chinese: '达到', definition: 'To reach or achieve something after effort.', synonyms: ['achieve', 'reach'], antonyms: ['fail', 'miss'], word_family: { noun: 'attainment' }, collocations: ['attain a goal', 'attain a standard'], example_sentence: 'Precision is a standard you attain by cutting, not by decorating.', edutest_frequency: 3, writing_value: 'Formal achievement verb.' },
  { word: 'attribute', level: 5, category: 'Academic', chinese: '归因于；特质', definition: 'To regard something as caused by; a quality belonging to a person.', synonyms: ['ascribe', 'quality'], antonyms: [], word_family: { noun: 'attribution' }, collocations: ['attribute to', 'key attribute'], example_sentence: 'Do not attribute the victory to luck until you have listed the hours of practice.', edutest_frequency: 4, writing_value: 'Noun and verb.' },
  { word: 'authentic', level: 5, category: 'Quality', chinese: '真实的', definition: 'Genuine; not copied, fake, or pretended.', synonyms: ['genuine', 'real'], antonyms: ['fake', 'counterfeit'], word_family: { noun: 'authenticity', adverb: 'authentically' }, collocations: ['authentic voice', 'authentic source'], example_sentence: 'An authentic voice in a story sounds like a person, not a brochure.', edutest_frequency: 4, writing_value: 'Style and honesty.' },
  { word: 'autonomy', level: 5, category: 'Academic', chinese: '自主', definition: 'The right or ability to make one’s own decisions.', synonyms: ['independence', 'self-rule'], antonyms: ['dependence', 'control'], word_family: { adjective: 'autonomous', adverb: 'autonomously' }, collocations: ['personal autonomy', 'greater autonomy'], example_sentence: 'Year 6 students want more autonomy, which is why trust matters more than extra rules.', edutest_frequency: 3, writing_value: 'Civic and character essays.' },
  { word: 'benevolent', level: 5, category: 'Character', chinese: '仁慈的', definition: 'Kind and wanting to do good.', synonyms: ['kind', 'charitable'], antonyms: ['malevolent', 'unkind'], word_family: { noun: 'benevolence', adverb: 'benevolently' }, collocations: ['benevolent smile', 'benevolent act'], example_sentence: 'A benevolent teacher can still mark strictly.', edutest_frequency: 3, writing_value: 'Formal kindness.' },
  { word: 'candid', level: 5, category: 'Character', chinese: '坦率的', definition: 'Honest and direct, even when the truth is uncomfortable.', synonyms: ['frank', 'blunt'], antonyms: ['evasive', 'guarded'], word_family: { noun: 'candour', adverb: 'candidly' }, collocations: ['candid remark', 'candid assessment'], example_sentence: 'Her candid assessment of the draft stung, and then it helped.', edutest_frequency: 3, writing_value: 'Voice.' },
  { word: 'comprehensive', level: 5, category: 'Academic', chinese: '全面的', definition: 'Including all or nearly all important parts.', synonyms: ['thorough', 'complete'], antonyms: ['partial', 'limited'], word_family: { adverb: 'comprehensively', noun: 'comprehensiveness' }, collocations: ['comprehensive review', 'comprehensive account'], example_sentence: 'A comprehensive review is not the same as an endless one.', edutest_frequency: 4, writing_value: 'Academic adjective.' },
  { word: 'contemporary', level: 5, category: 'Time', chinese: '当代的', definition: 'Belonging to the present time, or existing at the same time.', synonyms: ['modern', 'current'], antonyms: ['historical', 'old-fashioned'], word_family: {}, collocations: ['contemporary issue', 'contemporary of'], example_sentence: 'A contemporary issue can still be discussed with old-fashioned care.', edutest_frequency: 4, writing_value: 'History and current affairs.' },
  { word: 'controversial', level: 5, category: 'Academic', chinese: '有争议的', definition: 'Causing public disagreement or strong opposing views.', synonyms: ['disputed', 'contentious'], antonyms: ['uncontroversial', 'agreed'], word_family: { noun: 'controversy' }, collocations: ['controversial decision', 'controversial topic'], example_sentence: 'A controversial decision needs clearer reasons, not a louder announcement.', edutest_frequency: 4, writing_value: 'Discussion essays.' },
  { word: 'conventional', level: 5, category: 'Academic', chinese: '常规的', definition: 'Following accepted custom or the usual way of doing things.', synonyms: ['traditional', 'orthodox'], antonyms: ['unconventional', 'original'], word_family: { noun: 'convention', adverb: 'conventionally' }, collocations: ['conventional wisdom', 'conventional method'], example_sentence: 'Conventional wisdom said the quiet student would not debate; conventional wisdom was wrong.', edutest_frequency: 4, writing_value: 'Norms and originality.' },
  { word: 'cumulative', level: 5, category: 'Academic', chinese: '累积的', definition: 'Increasing by successive additions.', synonyms: ['accumulating', 'aggregate'], antonyms: ['isolated', 'one-off'], word_family: { verb: 'accumulate', noun: 'accumulation' }, collocations: ['cumulative effect', 'cumulative score'], example_sentence: 'Vocabulary has a cumulative effect: ten precise words change a whole page.', edutest_frequency: 3, writing_value: 'Process and progress.' },
  { word: 'detrimental', level: 5, category: 'Academic', chinese: '有害的', definition: 'Causing harm or damage.', synonyms: ['harmful', 'damaging'], antonyms: ['beneficial', 'helpful'], word_family: { noun: 'detriment' }, collocations: ['detrimental effect', 'detrimental to'], example_sentence: 'Sleep loss is more detrimental to a scholarship paper than an extra hour of cramming.', edutest_frequency: 4, writing_value: 'Formal harm word.' },
  { word: 'discrepancy', level: 5, category: 'Academic', chinese: '差异', definition: 'A difference between two things that should match.', synonyms: ['inconsistency', 'mismatch'], antonyms: ['agreement', 'consistency'], word_family: {}, collocations: ['discrepancy between', 'explain the discrepancy'], example_sentence: 'The discrepancy between the two witness statements is the beginning of the mystery.', edutest_frequency: 4, writing_value: 'Evidence analysis.' },
  { word: 'empirical', level: 5, category: 'Science', chinese: '实证的', definition: 'Based on observation or experiment rather than theory alone.', synonyms: ['observed', 'experimental'], antonyms: ['theoretical', 'speculative'], word_family: { noun: 'empiricism', adverb: 'empirically' }, collocations: ['empirical evidence', 'empirical study'], example_sentence: 'An empirical test of the creek water is worth more than a confident rumour.', edutest_frequency: 3, writing_value: 'Science register.' },
  { word: 'enigmatic', level: 5, category: 'Mystery', chinese: '神秘难解的', definition: 'Difficult to interpret; mysterious.', synonyms: ['mysterious', 'puzzling'], antonyms: ['obvious', 'transparent'], word_family: { noun: 'enigma' }, collocations: ['enigmatic smile', 'enigmatic figure'], example_sentence: 'The enigmatic smile in the photograph became the whole essay question.', edutest_frequency: 4, writing_value: 'Literary description.' },
  { word: 'ephemeral', level: 5, category: 'Time', chinese: '短暂的', definition: 'Lasting for a very short time.', synonyms: ['fleeting', 'transient'], antonyms: ['lasting', 'permanent'], word_family: { noun: 'ephemerality' }, collocations: ['ephemeral moment', 'ephemeral fame'], example_sentence: 'The applause was ephemeral; the improved habit was not.', edutest_frequency: 3, writing_value: 'High-level time word.' },
  { word: 'equivalent', level: 5, category: 'Academic', chinese: '等同的', definition: 'Equal in value, meaning, or effect.', synonyms: ['equal', 'corresponding'], antonyms: ['unequal', 'different'], word_family: { noun: 'equivalence' }, collocations: ['equivalent to', 'roughly equivalent'], example_sentence: 'A precise short answer can be equivalent to a long, wandering one — and better.', edutest_frequency: 4, writing_value: 'Comparison.' },
  { word: 'facilitate', level: 5, category: 'Academic', chinese: '促进', definition: 'To make an action or process easier.', synonyms: ['enable', 'assist'], antonyms: ['hinder', 'obstruct'], word_family: { noun: 'facilitation' }, collocations: ['facilitate discussion', 'facilitate learning'], example_sentence: 'Clear instructions facilitate speed; unclear ones waste it.', edutest_frequency: 4, writing_value: 'Formal help verb.' },
  { word: 'fundamental', level: 5, category: 'Academic', chinese: '根本的', definition: 'Forming a necessary base; of central importance.', synonyms: ['basic', 'essential'], antonyms: ['minor', 'incidental'], word_family: { adverb: 'fundamentally', noun: 'fundament' }, collocations: ['fundamental principle', 'fundamental error'], example_sentence: 'A fundamental error in reading the question cannot be repaired by beautiful handwriting.', edutest_frequency: 5, writing_value: 'Priority word.' },
  { word: 'implicit', level: 5, category: 'Academic', chinese: '含蓄的', definition: 'Suggested or understood without being directly stated.', synonyms: ['implied', 'unspoken'], antonyms: ['explicit', 'stated'], word_family: { adverb: 'implicitly' }, collocations: ['implicit meaning', 'implicit trust'], example_sentence: 'The criticism is implicit in the last adjective.', edutest_frequency: 5, writing_value: 'Pairs with explicit.' },
  { word: 'indigenous', level: 5, category: 'Academic', chinese: '本土的', definition: 'Originating in a particular place; native to a region.', synonyms: ['native', 'local'], antonyms: ['introduced', 'foreign'], word_family: {}, collocations: ['Indigenous Australians', 'indigenous species'], example_sentence: 'The garden used indigenous plants that could survive a dry January.', edutest_frequency: 4, writing_value: 'Australian context — capital I for people.' },
  { word: 'inevitable', level: 5, category: 'Academic', chinese: '不可避免的', definition: 'Certain to happen and unable to be avoided.', synonyms: ['unavoidable', 'certain'], antonyms: ['avoidable', 'uncertain'], word_family: { noun: 'inevitability', adverb: 'inevitably' }, collocations: ['inevitable result', 'almost inevitable'], example_sentence: 'If nobody checks the quote, a misread word is inevitable.', edutest_frequency: 5, writing_value: 'Logic and tone.' },
  { word: 'inherent', level: 5, category: 'Academic', chinese: '固有的', definition: 'Existing as a natural or permanent part of something.', synonyms: ['intrinsic', 'built-in'], antonyms: ['external', 'added'], word_family: { adverb: 'inherently' }, collocations: ['inherent risk', 'inherent quality'], example_sentence: 'There is an inherent risk in trusting a charming narrator.', edutest_frequency: 4, writing_value: 'Abstract analysis.' },
  { word: 'innovative', level: 5, category: 'Academic', chinese: '创新的', definition: 'Introducing new ideas or methods.', synonyms: ['original', 'inventive'], antonyms: ['conventional', 'unoriginal'], word_family: { noun: 'innovation', verb: 'innovate' }, collocations: ['innovative approach', 'innovative design'], example_sentence: 'An innovative approach is welcome if it still answers the question.', edutest_frequency: 3, writing_value: 'Positive evaluation.' },
  { word: 'integral', level: 5, category: 'Academic', chinese: '不可或缺的', definition: 'Necessary to make a whole complete.', synonyms: ['essential', 'indispensable'], antonyms: ['optional', 'peripheral'], word_family: {}, collocations: ['integral part', 'integral to'], example_sentence: 'Rereading is integral to comprehension, not a sign of weakness.', edutest_frequency: 4, writing_value: 'Importance.' },
  { word: 'legitimate', level: 5, category: 'Academic', chinese: '正当的', definition: 'Allowed by rules or reason; genuine.', synonyms: ['valid', 'lawful'], antonyms: ['illegitimate', 'invalid'], word_family: { noun: 'legitimacy', adverb: 'legitimately' }, collocations: ['legitimate concern', 'legitimate reason'], example_sentence: 'Fear of a hard paper is a legitimate feeling; skipping the reading is not a legitimate strategy.', edutest_frequency: 4, writing_value: 'Fairness word.' },
  { word: 'meticulous', level: 5, category: 'Character', chinese: '一丝不苟的', definition: 'Extremely careful about small details.', synonyms: ['thorough', 'fastidious'], antonyms: ['careless', 'sloppy'], word_family: { adverb: 'meticulously', noun: 'meticulousness' }, collocations: ['meticulous notes', 'meticulous care'], example_sentence: 'Meticulous notes are useless if they are never reread.', edutest_frequency: 5, writing_value: 'Scholarship work-habit word.' },
  { word: 'negligible', level: 5, category: 'Academic', chinese: '微不足道的', definition: 'So small that it can be ignored.', synonyms: ['insignificant', 'trivial'], antonyms: ['significant', 'considerable'], word_family: { noun: 'negligence' }, collocations: ['negligible difference', 'negligible risk'], example_sentence: 'The difference between the two options was not negligible; one word reversed the meaning.', edutest_frequency: 3, writing_value: 'Precision of scale.' },
  { word: 'ostentatious', level: 5, category: 'Character', chinese: '炫耀的', definition: 'Showy in a way meant to impress others.', synonyms: ['showy', 'pretentious'], antonyms: ['modest', 'understated'], word_family: { noun: 'ostentation', adverb: 'ostentatiously' }, collocations: ['ostentatious display', 'ostentatious language'], example_sentence: 'Ostentatious vocabulary is not the same as precise vocabulary.', edutest_frequency: 3, writing_value: 'Style warning.' },
  { word: 'paradox', level: 5, category: 'Academic', chinese: '悖论', definition: 'A statement or situation that seems contradictory but may be true.', synonyms: ['contradiction', 'puzzle'], antonyms: [], word_family: { adjective: 'paradoxical', adverb: 'paradoxically' }, collocations: ['seeming paradox', 'paradox of'], example_sentence: 'The paradox of the exam is that slowing down often saves time.', edutest_frequency: 4, writing_value: 'Idea word.' },
  { word: 'poignant', level: 5, category: 'Emotion', chinese: '辛酸感人的', definition: 'Evoking a sharp sense of sadness or regret.', synonyms: ['moving', 'touching'], antonyms: ['unmoving', 'cheerful'], word_family: { noun: 'poignancy', adverb: 'poignantly' }, collocations: ['poignant moment', 'poignant reminder'], example_sentence: 'The most poignant detail was the unused second lunch, packed by someone who hoped.', edutest_frequency: 4, writing_value: 'Literary emotion.' },
  { word: 'pragmatic', level: 5, category: 'Character', chinese: '务实的', definition: 'Dealing with things in a practical, realistic way.', synonyms: ['practical', 'realistic'], antonyms: ['idealistic', 'impractical'], word_family: { noun: 'pragmatism', adverb: 'pragmatically' }, collocations: ['pragmatic decision', 'pragmatic approach'], example_sentence: 'A pragmatic plan for the paper was to finish the sure marks before the beautiful ones.', edutest_frequency: 4, writing_value: 'Decision-making.' },
  { word: 'predominant', level: 5, category: 'Academic', chinese: '占主导的', definition: 'More important, powerful, or noticeable than others.', synonyms: ['main', 'prevailing'], antonyms: ['minor', 'secondary'], word_family: { noun: 'predominance', verb: 'predominate' }, collocations: ['predominant view', 'predominant colour'], example_sentence: 'The predominant tone of the letter is disappointment, not anger.', edutest_frequency: 3, writing_value: 'Tone questions.' },
  { word: 'preliminary', level: 5, category: 'Academic', chinese: '初步的', definition: 'Coming before the main event or discussion; introductory.', synonyms: ['initial', 'preparatory'], antonyms: ['final', 'conclusive'], word_family: {}, collocations: ['preliminary result', 'preliminary round'], example_sentence: 'A preliminary reading finds the topic; a second reading finds the attitude.', edutest_frequency: 3, writing_value: 'Process word.' },
  { word: 'prevalent', level: 5, category: 'Academic', chinese: '普遍的', definition: 'Widespread or commonly occurring at a particular time.', synonyms: ['widespread', 'common'], antonyms: ['rare', 'uncommon'], word_family: { noun: 'prevalence' }, collocations: ['prevalent belief', 'prevalent in'], example_sentence: 'A prevalent belief in the class was that speed equalled intelligence.', edutest_frequency: 3, writing_value: 'Social observation.' },
  { word: 'resilient', level: 5, category: 'Character', chinese: '有韧性的', definition: 'Able to recover quickly from difficulty.', synonyms: ['tough', 'adaptable'], antonyms: ['fragile', 'brittle'], word_family: { noun: 'resilience', adverb: 'resiliently' }, collocations: ['resilient student', 'resilient community'], example_sentence: 'A resilient student treats a poor practice paper as information, not as a verdict.', edutest_frequency: 5, writing_value: 'Scholarship interviews.' },
  { word: 'substantial', level: 5, category: 'Academic', chinese: '可观的', definition: 'Large in amount, importance, or worth.', synonyms: ['considerable', 'significant'], antonyms: ['slight', 'negligible'], word_family: { adverb: 'substantially', noun: 'substance' }, collocations: ['substantial evidence', 'substantial change'], example_sentence: 'You need substantial evidence, not a single convenient line.', edutest_frequency: 5, writing_value: 'Formal quantity.' },
  { word: 'superfluous', level: 5, category: 'Academic', chinese: '多余的', definition: 'More than is needed; unnecessary.', synonyms: ['unnecessary', 'redundant'], antonyms: ['essential', 'necessary'], word_family: { noun: 'superfluity' }, collocations: ['superfluous detail', 'superfluous word'], example_sentence: 'Cut the superfluous adjective and the sentence usually improves.', edutest_frequency: 4, writing_value: 'Editing word.' },
  { word: 'susceptible', level: 5, category: 'Academic', chinese: '易受影响的', definition: 'Likely to be influenced or harmed by something.', synonyms: ['vulnerable', 'prone'], antonyms: ['resistant', 'immune'], word_family: { noun: 'susceptibility' }, collocations: ['susceptible to', 'highly susceptible'], example_sentence: 'Tired readers are susceptible to the first attractive option.', edutest_frequency: 3, writing_value: 'Cause and risk.' },
  { word: 'tenacious', level: 5, category: 'Character', chinese: '顽强的', definition: 'Holding firmly to a purpose, idea, or position.', synonyms: ['persistent', 'determined'], antonyms: ['irresolute', 'yielding'], word_family: { noun: 'tenacity', adverb: 'tenaciously' }, collocations: ['tenacious grip', 'tenacious effort'], example_sentence: 'Tenacious rereading of one hard paragraph is often worth more than skimming three easy ones.', edutest_frequency: 4, writing_value: 'Character praise.' },
  { word: 'tentative', level: 5, category: 'Academic', chinese: '试探性的', definition: 'Not certain or fixed; done cautiously.', synonyms: ['provisional', 'hesitant'], antonyms: ['definite', 'confident'], word_family: { adverb: 'tentatively', noun: 'tentativeness' }, collocations: ['tentative conclusion', 'tentative step'], example_sentence: 'A tentative conclusion is honest when the evidence is thin.', edutest_frequency: 4, writing_value: 'Academic caution.' },
  { word: 'ubiquitous', level: 5, category: 'Academic', chinese: '无处不在的', definition: 'Seeming to be everywhere at once.', synonyms: ['omnipresent', 'pervasive'], antonyms: ['rare', 'scarce'], word_family: { noun: 'ubiquity' }, collocations: ['ubiquitous phones', 'almost ubiquitous'], example_sentence: 'The ubiquitous advice to "just be yourself" is unhelpful without a practised skill.', edutest_frequency: 3, writing_value: 'High-level description.' },
  { word: 'unprecedented', level: 5, category: 'Academic', chinese: '前所未有的', definition: 'Never known or done before.', synonyms: ['unheard-of', 'novel'], antonyms: ['familiar', 'precedented'], word_family: {}, collocations: ['unprecedented change', 'almost unprecedented'], example_sentence: 'An unprecedented heatwave does not excuse an unprecedented lack of planning.', edutest_frequency: 4, writing_value: 'News and history.' },
  { word: 'versatile', level: 5, category: 'Quality', chinese: '多才多艺的', definition: 'Able to be used, or to perform, in many different ways.', synonyms: ['adaptable', 'flexible'], antonyms: ['limited', 'specialised'], word_family: { noun: 'versatility' }, collocations: ['versatile player', 'versatile word'], example_sentence: 'A versatile word like "charge" changes meaning with context; that is why exams love it.', edutest_frequency: 3, writing_value: 'Flexibility praise.' },
  { word: 'viable', level: 5, category: 'Academic', chinese: '可行的', definition: 'Capable of working successfully.', synonyms: ['workable', 'feasible'], antonyms: ['unworkable', 'impractical'], word_family: { noun: 'viability' }, collocations: ['viable option', 'viable plan'], example_sentence: 'A viable study plan includes sleep, not only ambition.', edutest_frequency: 4, writing_value: 'Evaluation of plans.' },
  { word: 'acknowledge', level: 5, category: 'Academic', chinese: '承认', definition: 'To accept or admit that something is true or exists.', synonyms: ['admit', 'recognise'], antonyms: ['deny', 'ignore'], word_family: { noun: 'acknowledgement' }, collocations: ['acknowledge a mistake', 'acknowledge that'], example_sentence: 'Acknowledge the counter-argument if you want your own to look adult.', edutest_frequency: 5, writing_value: 'Essay maturity.' },
  { word: 'allocate', level: 5, category: 'Academic', chinese: '分配', definition: 'To set something aside for a particular purpose.', synonyms: ['assign', 'allot'], antonyms: ['withhold'], word_family: { noun: 'allocation' }, collocations: ['allocate time', 'allocate resources'], example_sentence: 'Allocate seven minutes to the hardest passage, then move on.', edutest_frequency: 3, writing_value: 'Exam strategy.' },
  { word: 'anticipate', level: 5, category: 'Academic', chinese: '预期', definition: 'To expect something and, often, prepare for it.', synonyms: ['expect', 'foresee'], antonyms: ['overlook'], word_family: { noun: 'anticipation' }, collocations: ['anticipate a problem', 'widely anticipated'], example_sentence: 'Anticipate a trap in any question that looks too kind.', edutest_frequency: 4, writing_value: 'Planning verb.' },
  { word: 'compile', level: 5, category: 'Academic', chinese: '汇编', definition: 'To collect information from different places and put it together.', synonyms: ['assemble', 'gather'], antonyms: ['scatter'], word_family: { noun: 'compilation' }, collocations: ['compile notes', 'compile a list'], example_sentence: 'Compile your error list weekly or you will sit the same trap again.', edutest_frequency: 3, writing_value: 'Study verb.' },
  { word: 'comply', level: 5, category: 'Academic', chinese: '遵守', definition: 'To act in accordance with a rule or request.', synonyms: ['obey', 'observe'], antonyms: ['defy', 'disobey'], word_family: { noun: 'compliance', adjective: 'compliant' }, collocations: ['comply with', 'fail to comply'], example_sentence: 'Students must comply with the silent-paper rule even when the clock feels cruel.', edutest_frequency: 3, writing_value: 'Formal rules.' },
  { word: 'constitute', level: 5, category: 'Academic', chinese: '构成', definition: 'To be the parts or the official making of something.', synonyms: ['form', 'make up'], antonyms: [], word_family: { noun: 'constitution' }, collocations: ['constitute a majority', 'constitute evidence'], example_sentence: 'Two similar mistakes can constitute a pattern.', edutest_frequency: 4, writing_value: 'Formal "make up".' },
  { word: 'deduce', level: 5, category: 'Academic', chinese: '推断', definition: 'To reach a logical conclusion from known facts.', synonyms: ['infer', 'conclude'], antonyms: ['guess wildly'], word_family: { noun: 'deduction' }, collocations: ['deduce from', 'reasonably deduce'], example_sentence: 'From the muddy shoes and the early bell, they could deduce he had run.', edutest_frequency: 5, writing_value: 'Logic verb.' },
  { word: 'differentiate', level: 5, category: 'Academic', chinese: '区分', definition: 'To recognise or show the difference between things.', synonyms: ['distinguish', 'separate'], antonyms: ['confuse', 'conflate'], word_family: { noun: 'differentiation' }, collocations: ['differentiate between', 'differentiate a term'], example_sentence: 'Differentiate "imply" from "infer" and you will stop losing easy marks.', edutest_frequency: 4, writing_value: 'Precision verb.' },
];
