import type { VocabularyLevel, WordFamily } from '../types';

type SeedRow = {
  word: string;
  level: VocabularyLevel;
  category: string;
  chinese: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  word_family: WordFamily;
  collocations: string[];
  example_sentence: string;
  edutest_frequency: number;
  writing_value: string;
};

export const L4: SeedRow[] = [
  { word: 'analyse', level: 4, category: 'Academic', chinese: '分析', definition: 'To examine something carefully by breaking it into parts.', synonyms: ['examine', 'dissect'], antonyms: ['ignore', 'gloss over'], word_family: { noun: 'analysis', adjective: 'analytical' }, collocations: ['analyse a text', 'analyse the results'], example_sentence: 'Analyse the narrator’s word choice before you decide he is cruel.', edutest_frequency: 5, writing_value: 'Australian spelling; core exam verb.' },
  { word: 'argument', level: 4, category: 'Academic', chinese: '论点', definition: 'A reasoned case for a claim, supported by evidence.', synonyms: ['case', 'contention'], antonyms: ['agreement'], word_family: { verb: 'argue', adjective: 'argumentative' }, collocations: ['construct an argument', 'central argument'], example_sentence: 'A shouting match is not an argument; an argument has reasons.', edutest_frequency: 5, writing_value: 'Essay structure word.' },
  { word: 'assess', level: 4, category: 'Academic', chinese: '评估', definition: 'To judge the value, quality, or importance of something.', synonyms: ['evaluate', 'judge'], antonyms: ['ignore'], word_family: { noun: 'assessment', adjective: 'assessable' }, collocations: ['assess the evidence', 'assess risk'], example_sentence: 'Assess the evidence before you accept the headline.', edutest_frequency: 5, writing_value: 'Exam instruction.' },
  { word: 'assume', level: 4, category: 'Academic', chinese: '假定', definition: 'To accept something as true without proof.', synonyms: ['presume', 'suppose'], antonyms: ['verify', 'prove'], word_family: { noun: 'assumption' }, collocations: ['assume that', 'false assumption'], example_sentence: 'Do not assume the first speaker is the hero.', edutest_frequency: 5, writing_value: 'Critical-reading verb.' },
  { word: 'benefit', level: 4, category: 'Academic', chinese: '益处', definition: 'An advantage or helpful result.', synonyms: ['advantage', 'gain'], antonyms: ['drawback', 'harm'], word_family: { adjective: 'beneficial', adverb: 'beneficially' }, collocations: ['benefit from', 'clear benefit'], example_sentence: 'The benefit of a second draft is not length; it is accuracy.', edutest_frequency: 4, writing_value: 'Evaluation essays.' },
  { word: 'category', level: 4, category: 'Academic', chinese: '类别', definition: 'A group of things that share important features.', synonyms: ['class', 'type'], antonyms: [], word_family: { verb: 'categorise', adjective: 'categorical' }, collocations: ['fit a category', 'broad category'], example_sentence: 'Place the question in a category before you hunt for a trick.', edutest_frequency: 4, writing_value: 'Organisation word.' },
  { word: 'complex', level: 4, category: 'Academic', chinese: '复杂的', definition: 'Made of many connected parts; not simple.', synonyms: ['complicated', 'intricate'], antonyms: ['simple', 'straightforward'], word_family: { noun: 'complexity', adverb: 'complexly' }, collocations: ['complex problem', 'complex character'], example_sentence: 'A complex character can be kind and still be wrong.', edutest_frequency: 5, writing_value: 'Text-response gold.' },
  { word: 'component', level: 4, category: 'Academic', chinese: '组成部分', definition: 'One of the parts that together make a whole.', synonyms: ['element', 'part'], antonyms: ['whole'], word_family: {}, collocations: ['key component', 'component of'], example_sentence: 'Evidence is a component of an argument, not a decoration.', edutest_frequency: 4, writing_value: 'Science and essays.' },
  { word: 'concept', level: 4, category: 'Academic', chinese: '概念', definition: 'An idea or general principle.', synonyms: ['idea', 'notion'], antonyms: [], word_family: { adjective: 'conceptual', verb: 'conceptualise' }, collocations: ['key concept', 'abstract concept'], example_sentence: 'Fairness is a concept; a rule is only one attempt to apply it.', edutest_frequency: 5, writing_value: 'Abstract thinking.' },
  { word: 'consequence', level: 4, category: 'Academic', chinese: '后果', definition: 'A result that follows from an action or condition.', synonyms: ['result', 'outcome'], antonyms: ['cause'], word_family: { adjective: 'consequential' }, collocations: ['serious consequence', 'as a consequence'], example_sentence: 'Every choice in the story has a consequence the writer wants you to notice.', edutest_frequency: 5, writing_value: 'Cause and effect.' },
  { word: 'context', level: 4, category: 'Academic', chinese: '语境；背景', definition: 'The surrounding words, situation, or background that give meaning.', synonyms: ['setting', 'background'], antonyms: [], word_family: { adjective: 'contextual' }, collocations: ['in context', 'historical context'], example_sentence: 'A hard word is easier in context than in a list.', edutest_frequency: 5, writing_value: 'Vocabulary-in-context questions.' },
  { word: 'contrast', level: 4, category: 'Academic', chinese: '对比', definition: 'A clear difference, or the act of showing differences.', synonyms: ['difference', 'distinction'], antonyms: ['similarity'], word_family: { adjective: 'contrasting' }, collocations: ['in contrast', 'sharp contrast'], example_sentence: 'Contrast the two openings: one flatters the reader, one challenges him.', edutest_frequency: 5, writing_value: 'Compare/contrast essays.' },
  { word: 'criterion', level: 4, category: 'Academic', chinese: '标准', definition: 'A standard by which something is judged (plural: criteria).', synonyms: ['standard', 'measure'], antonyms: [], word_family: {}, collocations: ['meet a criterion', 'selection criteria'], example_sentence: 'One criterion for a strong sentence is that every word earns its place.', edutest_frequency: 4, writing_value: 'Formal academic noun.' },
  { word: 'data', level: 4, category: 'Academic', chinese: '数据', definition: 'Facts or measurements collected for study.', synonyms: ['information', 'figures'], antonyms: [], word_family: {}, collocations: ['collect data', 'interpret data'], example_sentence: 'The data did not match the first guess, so the guess had to go.', edutest_frequency: 4, writing_value: 'Science writing.' },
  { word: 'define', level: 4, category: 'Academic', chinese: '定义', definition: 'To state the exact meaning of a word or idea.', synonyms: ['specify', 'clarify'], antonyms: ['obscure'], word_family: { noun: 'definition', adjective: 'definite' }, collocations: ['define a term', 'clearly define'], example_sentence: 'Define the problem before you invent a solution.', edutest_frequency: 4, writing_value: 'Precision.' },
  { word: 'derive', level: 4, category: 'Academic', chinese: '得出', definition: 'To obtain something from a source, or to reach a conclusion.', synonyms: ['obtain', 'deduce'], antonyms: [], word_family: { noun: 'derivation' }, collocations: ['derive from', 'derive a conclusion'], example_sentence: 'What conclusion can you derive from the last two sentences together?', edutest_frequency: 4, writing_value: 'Reasoning verb.' },
  { word: 'element', level: 4, category: 'Academic', chinese: '要素', definition: 'An essential part of something.', synonyms: ['component', 'factor'], antonyms: [], word_family: { adjective: 'elemental' }, collocations: ['key element', 'element of surprise'], example_sentence: 'Suspense is an element of the passage, not the whole point.', edutest_frequency: 4, writing_value: 'Analysis noun.' },
  { word: 'establish', level: 4, category: 'Academic', chinese: '确立', definition: 'To set up, or to show that something is true.', synonyms: ['found', 'prove'], antonyms: ['disprove', 'abolish'], word_family: { noun: 'establishment' }, collocations: ['establish a fact', 'establish a school'], example_sentence: 'The first paragraph must establish the conflict, not wander.', edutest_frequency: 5, writing_value: 'Essay openings.' },
  { word: 'estimate', level: 4, category: 'Academic', chinese: '估计', definition: 'To judge an amount or value roughly, using available information.', synonyms: ['approximate', 'gauge'], antonyms: ['measure exactly'], word_family: { noun: 'estimation' }, collocations: ['rough estimate', 'estimate the cost'], example_sentence: 'Estimate the word count; then cut the sentence that repeats itself.', edutest_frequency: 3, writing_value: 'Numeracy + judgement.' },
  { word: 'evaluate', level: 4, category: 'Academic', chinese: '评价', definition: 'To judge how good, useful, or successful something is.', synonyms: ['assess', 'appraise'], antonyms: [], word_family: { noun: 'evaluation', adjective: 'evaluative' }, collocations: ['evaluate an argument', 'evaluate the method'], example_sentence: 'Evaluate the argument, not the person making it.', edutest_frequency: 5, writing_value: 'Highest-order exam verb.' },
  { word: 'evidence', level: 4, category: 'Academic', chinese: '证据', definition: 'Facts or details that support a belief or conclusion.', synonyms: ['proof', 'support'], antonyms: [], word_family: { adjective: 'evident' }, collocations: ['textual evidence', 'lack of evidence'], example_sentence: 'Opinion without evidence is just volume.', edutest_frequency: 5, writing_value: 'Core academic noun.' },
  { word: 'factor', level: 4, category: 'Academic', chinese: '因素', definition: 'One of the things that influences a result.', synonyms: ['element', 'influence'], antonyms: [], word_family: {}, collocations: ['key factor', 'factor in'], example_sentence: 'Time of day was a factor in how carefully they read.', edutest_frequency: 4, writing_value: 'Explanation essays.' },
  { word: 'function', level: 4, category: 'Academic', chinese: '功能', definition: 'The purpose or job that something has.', synonyms: ['purpose', 'role'], antonyms: [], word_family: { adjective: 'functional' }, collocations: ['main function', 'function as'], example_sentence: 'What is the function of the short final paragraph?', edutest_frequency: 5, writing_value: 'Language-analysis question.' },
  { word: 'hypothesis', level: 4, category: 'Science', chinese: '假设', definition: 'A possible explanation that can be tested.', synonyms: ['theory', 'proposition'], antonyms: [], word_family: { plural: 'hypotheses', adjective: 'hypothetical' }, collocations: ['test a hypothesis', 'working hypothesis'], example_sentence: 'A hypothesis is a disciplined guess, not a wild one.', edutest_frequency: 5, writing_value: 'Science writing.' },
  { word: 'illustrate', level: 4, category: 'Academic', chinese: '说明', definition: 'To make an idea clearer with an example or image.', synonyms: ['exemplify', 'show'], antonyms: [], word_family: { noun: 'illustration', adjective: 'illustrative' }, collocations: ['illustrate a point', 'clearly illustrate'], example_sentence: 'One concrete scene can illustrate a claim better than three adjectives.', edutest_frequency: 4, writing_value: 'Explanation verb.' },
  { word: 'implication', level: 4, category: 'Academic', chinese: '含义；影响', definition: 'Something suggested without being said directly, or a likely result.', synonyms: ['suggestion', 'consequence'], antonyms: [], word_family: { verb: 'imply' }, collocations: ['implication of', 'serious implication'], example_sentence: 'The implication of the last line is that nobody has told the truth yet.', edutest_frequency: 5, writing_value: 'Inference noun.' },
  { word: 'infer', level: 4, category: 'Academic', chinese: '推断', definition: 'To reach a conclusion from evidence rather than from a direct statement.', synonyms: ['deduce', 'conclude'], antonyms: ['state'], word_family: { noun: 'inference' }, collocations: ['infer from', 'reasonably infer'], example_sentence: 'What can the reader infer about the missing letter?', edutest_frequency: 5, writing_value: 'EduTest staple.' },
  { word: 'interpret', level: 4, category: 'Academic', chinese: '解释', definition: 'To explain the meaning of words, data, or events.', synonyms: ['explain', 'construe'], antonyms: ['misread'], word_family: { noun: 'interpretation' }, collocations: ['interpret a passage', 'interpret data'], example_sentence: 'Two readers can interpret the same silence in opposite ways; both need evidence.', edutest_frequency: 5, writing_value: 'Comprehension verb.' },
  { word: 'investigate', level: 4, category: 'Academic', chinese: '调查', definition: 'To examine the facts of a situation carefully.', synonyms: ['examine', 'probe'], antonyms: ['ignore'], word_family: { noun: 'investigation', adjective: 'investigative' }, collocations: ['investigate a claim', 'investigate further'], example_sentence: 'Investigate the unusual word before you skip it.', edutest_frequency: 4, writing_value: 'Inquiry verb.' },
  { word: 'justify', level: 4, category: 'Academic', chinese: '证明合理', definition: 'To give reasons that show why something is right or reasonable.', synonyms: ['defend', 'support'], antonyms: ['undermine'], word_family: { noun: 'justification' }, collocations: ['justify a choice', 'justify the answer'], example_sentence: 'Justify your answer with a phrase from the passage, not with "I just think".', edutest_frequency: 5, writing_value: 'Short-answer gold.' },
  { word: 'method', level: 4, category: 'Academic', chinese: '方法', definition: 'A planned way of doing something.', synonyms: ['approach', 'procedure'], antonyms: [], word_family: { adjective: 'methodical', adverb: 'methodically' }, collocations: ['scientific method', 'method of'], example_sentence: 'A methodical check of units prevents a certain kind of disaster.', edutest_frequency: 4, writing_value: 'Process word.' },
  { word: 'occur', level: 4, category: 'Academic', chinese: '发生', definition: 'To happen, or to come into the mind.', synonyms: ['happen', 'take place'], antonyms: [], word_family: { noun: 'occurrence' }, collocations: ['occur when', 'it occurred to'], example_sentence: 'It occurred to him that the easiest option was also the least honest.', edutest_frequency: 4, writing_value: 'Formal alternative to "happen".' },
  { word: 'outcome', level: 4, category: 'Academic', chinese: '结果', definition: 'The result of a process, test, or decision.', synonyms: ['result', 'consequence'], antonyms: [], word_family: {}, collocations: ['likely outcome', 'final outcome'], example_sentence: 'The outcome of rushing is usually a neat page with the wrong answer.', edutest_frequency: 4, writing_value: 'Report noun.' },
  { word: 'perspective', level: 4, category: 'Academic', chinese: '视角', definition: 'A particular way of seeing or thinking about something.', synonyms: ['viewpoint', 'standpoint'], antonyms: [], word_family: {}, collocations: ['from the perspective of', 'shift in perspective'], example_sentence: 'A shift in perspective at the end of a story is often the whole point.', edutest_frequency: 5, writing_value: 'Narrative and argument.' },
  { word: 'phenomenon', level: 4, category: 'Science', chinese: '现象', definition: 'A fact or event that can be observed, especially one that is unusual.', synonyms: ['occurrence', 'event'], antonyms: [], word_family: { plural: 'phenomena' }, collocations: ['natural phenomenon', 'explain a phenomenon'], example_sentence: 'A mirage is a phenomenon, not a hallucination you can argue with.', edutest_frequency: 4, writing_value: 'Science register.' },
  { word: 'predict', level: 4, category: 'Academic', chinese: '预测', definition: 'To say what is likely to happen, based on evidence.', synonyms: ['forecast', 'foretell'], antonyms: [], word_family: { noun: 'prediction', adjective: 'predictable' }, collocations: ['predict the result', 'hard to predict'], example_sentence: 'Predict the ending only after you have noticed the pattern.', edutest_frequency: 4, writing_value: 'Science and narrative.' },
  { word: 'previous', level: 4, category: 'Academic', chinese: '先前的', definition: 'Coming before in time or order.', synonyms: ['earlier', 'prior'], antonyms: ['following', 'subsequent'], word_family: { adverb: 'previously' }, collocations: ['previous chapter', 'previous attempt'], example_sentence: 'The previous paragraph already answered the question you are still worrying about.', edutest_frequency: 4, writing_value: 'Cohesion word.' },
  { word: 'primary', level: 4, category: 'Academic', chinese: '主要的；初级的', definition: 'First in importance, or first in a sequence.', synonyms: ['main', 'chief'], antonyms: ['secondary'], word_family: { adverb: 'primarily' }, collocations: ['primary reason', 'primary source'], example_sentence: 'The primary reason for the delay was not weather; it was a locked gate.', edutest_frequency: 5, writing_value: 'Priority word.' },
  { word: 'principle', level: 4, category: 'Academic', chinese: '原则', definition: 'A basic rule, belief, or truth that guides action.', synonyms: ['rule', 'tenet'], antonyms: [], word_family: { adjective: 'principled' }, collocations: ['guiding principle', 'in principle'], example_sentence: 'In principle the rule was fair; in practice it punished the late bus.', edutest_frequency: 5, writing_value: 'Not "principal".' },
  { word: 'procedure', level: 4, category: 'Academic', chinese: '程序', definition: 'An agreed series of actions for doing a task.', synonyms: ['process', 'method'], antonyms: [], word_family: { adjective: 'procedural' }, collocations: ['safety procedure', 'follow the procedure'], example_sentence: 'The procedure was posted on the wall, which did not stop people from inventing a faster one.', edutest_frequency: 3, writing_value: 'Science write-ups.' },
  { word: 'process', level: 4, category: 'Academic', chinese: '过程', definition: 'A series of actions that produce a result.', synonyms: ['procedure', 'course'], antonyms: [], word_family: {}, collocations: ['learning process', 'process of'], example_sentence: 'Revision is a process, not a single heroic night.', edutest_frequency: 4, writing_value: 'Abstract noun.' },
  { word: 'relevant', level: 4, category: 'Academic', chinese: '相关的', definition: 'Closely connected to the matter being considered.', synonyms: ['pertinent', 'applicable'], antonyms: ['irrelevant', 'beside the point'], word_family: { noun: 'relevance' }, collocations: ['relevant evidence', 'relevant to'], example_sentence: 'A beautiful sentence is still a waste if it is not relevant.', edutest_frequency: 5, writing_value: 'Editing and answers.' },
  { word: 'research', level: 4, category: 'Academic', chinese: '研究', definition: 'Careful study to discover or check facts.', synonyms: ['investigation', 'inquiry'], antonyms: [], word_family: { noun: 'researcher' }, collocations: ['research a topic', 'recent research'], example_sentence: 'Research a word’s family and you will remember it longer than a translation will allow.', edutest_frequency: 4, writing_value: 'Study noun/verb.' },
  { word: 'resource', level: 4, category: 'Academic', chinese: '资源', definition: 'Something that can be used to help achieve a goal.', synonyms: ['asset', 'supply'], antonyms: [], word_family: { adjective: 'resourceful' }, collocations: ['limited resource', 'resourceful student'], example_sentence: 'Time is a resource; spending it on panic is a poor investment.', edutest_frequency: 3, writing_value: 'Plus "resourceful".' },
  { word: 'respond', level: 4, category: 'Academic', chinese: '回应', definition: 'To reply or react, in words or action.', synonyms: ['reply', 'react'], antonyms: ['ignore'], word_family: { noun: 'response', adjective: 'responsive' }, collocations: ['respond to', 'considered response'], example_sentence: 'Respond to the question that was asked, not the one you wished had been asked.', edutest_frequency: 5, writing_value: 'Exam instruction.' },
  { word: 'role', level: 4, category: 'Academic', chinese: '作用；角色', definition: 'The function or part played by a person or thing.', synonyms: ['function', 'part'], antonyms: [], word_family: {}, collocations: ['play a role', 'role of'], example_sentence: 'What role does the weather play in the character’s decision?', edutest_frequency: 4, writing_value: 'Analysis question stem.' },
  { word: 'sequence', level: 4, category: 'Academic', chinese: '顺序', definition: 'The order in which things follow one another.', synonyms: ['order', 'series'], antonyms: [], word_family: { adjective: 'sequential', adverb: 'sequentially' }, collocations: ['logical sequence', 'sequence of events'], example_sentence: 'A muddled sequence of events is often why a narrative loses marks.', edutest_frequency: 4, writing_value: 'Structure.' },
  { word: 'significant', level: 4, category: 'Academic', chinese: '重要的', definition: 'Important enough to be worth noticing or discussing.', synonyms: ['important', 'noteworthy'], antonyms: ['insignificant', 'trivial'], word_family: { noun: 'significance', adverb: 'significantly' }, collocations: ['significant change', 'significant detail'], example_sentence: 'A significant detail is usually repeated, stressed, or strangely ordinary.', edutest_frequency: 5, writing_value: 'Upgrade from "big".' },
  { word: 'source', level: 4, category: 'Academic', chinese: '来源', definition: 'The place, person, or text from which something comes.', synonyms: ['origin', 'reference'], antonyms: [], word_family: {}, collocations: ['primary source', 'source of'], example_sentence: 'Name the source of a fact, or do not treat it as a fact.', edutest_frequency: 4, writing_value: 'Research honesty.' },
  { word: 'specific', level: 4, category: 'Academic', chinese: '具体的', definition: 'Clearly identified; particular rather than general.', synonyms: ['particular', 'precise'], antonyms: ['general', 'vague'], word_family: { adverb: 'specifically', noun: 'specificity' }, collocations: ['specific example', 'be specific'], example_sentence: 'Be specific: "the cracked compass" is better than "the thing".', edutest_frequency: 5, writing_value: 'Writing quality.' },
  { word: 'strategy', level: 4, category: 'Academic', chinese: '策略', definition: 'A planned method for achieving a goal.', synonyms: ['plan', 'approach'], antonyms: [], word_family: { adjective: 'strategic', adverb: 'strategically' }, collocations: ['exam strategy', 'strategy for'], example_sentence: 'A strategy for hard passages is to mark names, times, and shifts in tone.', edutest_frequency: 4, writing_value: 'Metacognition.' },
  { word: 'structure', level: 4, category: 'Academic', chinese: '结构', definition: 'The way parts are arranged to form a whole.', synonyms: ['framework', 'organisation'], antonyms: [], word_family: { verb: 'structure', adjective: 'structural' }, collocations: ['essay structure', 'structure of'], example_sentence: 'The structure of the passage — claim, example, twist — is itself a clue.', edutest_frequency: 5, writing_value: 'Text analysis.' },
  { word: 'subsequent', level: 4, category: 'Academic', chinese: '随后的', definition: 'Coming after something else in time.', synonyms: ['later', 'following'], antonyms: ['previous', 'prior'], word_family: { adverb: 'subsequently' }, collocations: ['subsequent events', 'subsequent chapter'], example_sentence: 'Subsequent events make the first promise look either brave or foolish.', edutest_frequency: 4, writing_value: 'Formal time word.' },
  { word: 'sufficient', level: 4, category: 'Academic', chinese: '足够的', definition: 'As much as is needed; enough.', synonyms: ['adequate', 'enough'], antonyms: ['insufficient', 'inadequate'], word_family: { noun: 'sufficiency', adverb: 'sufficiently' }, collocations: ['sufficient evidence', 'sufficient time'], example_sentence: 'Two precise quotes are sufficient; five vague ones are not.', edutest_frequency: 5, writing_value: 'Formal "enough".' },
  { word: 'theory', level: 4, category: 'Academic', chinese: '理论', definition: 'A system of ideas that explains something, or an unproven idea.', synonyms: ['explanation', 'hypothesis'], antonyms: [], word_family: { adjective: 'theoretical', adverb: 'theoretically' }, collocations: ['in theory', 'working theory'], example_sentence: 'In theory the shortcut saved time; in practice it cost the mark.', edutest_frequency: 4, writing_value: 'Academic noun.' },
  { word: 'valid', level: 4, category: 'Academic', chinese: '有效的', definition: 'Based on truth or sound reasoning; legally or logically acceptable.', synonyms: ['sound', 'legitimate'], antonyms: ['invalid', 'flawed'], word_family: { noun: 'validity', adverb: 'validly' }, collocations: ['valid point', 'valid reason'], example_sentence: 'A valid point can still be incomplete.', edutest_frequency: 4, writing_value: 'Argument quality.' },
  { word: 'vary', level: 4, category: 'Academic', chinese: '变化', definition: 'To differ, or to change within a range.', synonyms: ['differ', 'fluctuate'], antonyms: ['stay constant'], word_family: { noun: 'variation', adjective: 'variable' }, collocations: ['vary from', 'opinions vary'], example_sentence: 'Answers will vary, but the best ones still quote the text.', edutest_frequency: 3, writing_value: 'Science and writing.' },
  { word: 'achieve', level: 4, category: 'Academic', chinese: '实现', definition: 'To succeed in reaching a goal, especially after effort.', synonyms: ['attain', 'accomplish'], antonyms: ['fail'], word_family: { noun: 'achievement' }, collocations: ['achieve a goal', 'hard-won achievement'], example_sentence: 'You do not achieve a scholarship by collecting long words; you achieve it by using the right ones.', edutest_frequency: 4, writing_value: 'Goal language.' },
  { word: 'acquire', level: 4, category: 'Academic', chinese: '获得', definition: 'To gain or come to have something, especially knowledge or a skill.', synonyms: ['obtain', 'gain'], antonyms: ['lose'], word_family: { noun: 'acquisition' }, collocations: ['acquire knowledge', 'acquire a habit'], example_sentence: 'Students acquire vocabulary faster when they meet it in a passage, not only in a list.', edutest_frequency: 4, writing_value: 'Formal "get".' },
  { word: 'appropriate', level: 4, category: 'Academic', chinese: '恰当的', definition: 'Suitable for a particular purpose, person, or situation.', synonyms: ['suitable', 'fitting'], antonyms: ['inappropriate', 'unsuitable'], word_family: { adverb: 'appropriately', noun: 'appropriateness' }, collocations: ['appropriate tone', 'appropriate example'], example_sentence: 'An appropriate tone for a scholarship letter is respectful, not theatrical.', edutest_frequency: 5, writing_value: 'Register word.' },
];
