import type { VocabularyEntry, VocabularyLevel, WordFamily } from '../types';
import { L2 } from './seed-l2';
import { L3 } from './seed-l3';
import { L4 } from './seed-l4';
import { L5 } from './seed-l5';

type SeedRow = {
  word: string;
  level: VocabularyLevel;
  category: string;
  chinese: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  word_family: WordFamily;
  collocations: string[];
  example_sentence: string;
  edutest_frequency: number;
  writing_value: string;
};

const L1: SeedRow[] = [
  { word: 'abundant', level: 1, category: 'Quantity', chinese: '丰富的', definition: 'Present in a large amount; more than enough.', synonyms: ['plentiful', 'ample'], antonyms: ['scarce', 'meagre'], word_family: { noun: 'abundance', adverb: 'abundantly' }, collocations: ['abundant evidence', 'abundant rainfall'], example_sentence: 'The library offered abundant evidence for both sides of the debate.', edutest_frequency: 4, writing_value: 'Stronger than "lots of" in reports.' },
  { word: 'accurate', level: 1, category: 'Quality', chinese: '准确的', definition: 'Correct in every important detail.', synonyms: ['precise', 'exact'], antonyms: ['inaccurate', 'faulty'], word_family: { noun: 'accuracy', adverb: 'accurately' }, collocations: ['accurate account', 'accurate measurement'], example_sentence: 'An accurate account of the experiment must include the unexpected result.', edutest_frequency: 5, writing_value: 'Essential for science and comprehension answers.' },
  { word: 'adapt', level: 1, category: 'Action', chinese: '适应', definition: 'To change behaviour or method so that it fits a new situation.', synonyms: ['adjust', 'modify'], antonyms: ['resist', 'refuse'], word_family: { noun: 'adaptation', adjective: 'adaptable' }, collocations: ['adapt to change', 'adapt a plan'], example_sentence: 'Oliver had to adapt his study routine when cricket training moved to Thursday nights.', edutest_frequency: 5, writing_value: 'Useful for character growth and problem-solving.' },
  { word: 'advise', level: 1, category: 'Communication', chinese: '建议', definition: 'To give someone a thoughtful recommendation about what to do.', synonyms: ['recommend', 'counsel'], antonyms: ['mislead', 'discourage'], word_family: { noun: 'advice', adjective: 'advisable' }, collocations: ['advise against', 'strongly advise'], example_sentence: 'The teacher did not order him to rewrite the paragraph; she advised him to tighten the opening.', edutest_frequency: 4, writing_value: 'Separates the verb from the noun "advice".' },
  { word: 'ancient', level: 1, category: 'Time', chinese: '古老的', definition: 'Belonging to a time long ago; very old.', synonyms: ['age-old', 'antique'], antonyms: ['modern', 'recent'], word_family: { noun: 'ancientness' }, collocations: ['ancient civilisation', 'ancient tradition'], example_sentence: 'The museum case held an ancient compass used on early coastal voyages.', edutest_frequency: 4, writing_value: 'Sets historical atmosphere quickly.' },
  { word: 'anxious', level: 1, category: 'Emotion', chinese: '焦虑的', definition: 'Feeling worried or uneasy about what may happen.', synonyms: ['uneasy', 'apprehensive'], antonyms: ['calm', 'relaxed'], word_family: { noun: 'anxiety', adverb: 'anxiously' }, collocations: ['anxious about', 'anxious wait'], example_sentence: 'He felt anxious before the scholarship paper, but he still read the first question twice.', edutest_frequency: 5, writing_value: 'More precise than "nervous" in narrative.' },
  { word: 'apparent', level: 1, category: 'Observation', chinese: '明显的', definition: 'Easy to see or understand; seeming to be true.', synonyms: ['clear', 'evident'], antonyms: ['hidden', 'obscure'], word_family: { adverb: 'apparently', noun: 'appearance' }, collocations: ['apparent reason', 'become apparent'], example_sentence: 'It became apparent that the missing page had been torn out, not lost.', edutest_frequency: 4, writing_value: 'Useful for inference questions.' },
  { word: 'approach', level: 1, category: 'Action', chinese: '接近；方法', definition: 'To come nearer, or a way of dealing with a task.', synonyms: ['method', 'advance'], antonyms: ['retreat', 'avoid'], word_family: { adjective: 'approachable' }, collocations: ['approach the problem', 'careful approach'], example_sentence: 'A careful approach to the comprehension passage saved him from a trap in question three.', edutest_frequency: 5, writing_value: 'Works as noun or verb in academic writing.' },
  { word: 'awkward', level: 1, category: 'Social', chinese: '尴尬的；笨拙的', definition: 'Uncomfortable, clumsy, or difficult to handle.', synonyms: ['clumsy', 'uncomfortable'], antonyms: ['graceful', 'easy'], word_family: { noun: 'awkwardness', adverb: 'awkwardly' }, collocations: ['awkward silence', 'awkward position'], example_sentence: 'An awkward silence followed when nobody wanted to admit the mistake.', edutest_frequency: 3, writing_value: 'Good for social tension in stories.' },
  { word: 'brief', level: 1, category: 'Description', chinese: '简短的', definition: 'Lasting only a short time; using few words.', synonyms: ['short', 'concise'], antonyms: ['lengthy', 'extended'], word_family: { adverb: 'briefly', noun: 'brevity' }, collocations: ['brief visit', 'brief summary'], example_sentence: 'The examiner asked for a brief summary, not a retelling of every sentence.', edutest_frequency: 4, writing_value: 'Signals control of length in writing.' },
  { word: 'capable', level: 1, category: 'Character', chinese: '有能力的', definition: 'Having the skill or quality needed to do something well.', synonyms: ['able', 'competent'], antonyms: ['incapable', 'inept'], word_family: { noun: 'capability', adverb: 'capably' }, collocations: ['capable of', 'highly capable'], example_sentence: 'She was capable of solving the puzzle, but she refused to rush.', edutest_frequency: 4, writing_value: 'Stronger character word than "good at".' },
  { word: 'cautious', level: 1, category: 'Character', chinese: '谨慎的', definition: 'Careful to avoid danger, error, or unnecessary risk.', synonyms: ['careful', 'wary'], antonyms: ['reckless', 'hasty'], word_family: { noun: 'caution', adverb: 'cautiously' }, collocations: ['cautious approach', 'cautious optimism'], example_sentence: 'A cautious reader checks whether the narrator can be trusted.', edutest_frequency: 4, writing_value: 'Useful contrast with impulsive characters.' },
  { word: 'cease', level: 1, category: 'Action', chinese: '停止', definition: 'To come to an end or to stop doing something.', synonyms: ['stop', 'halt'], antonyms: ['continue', 'persist'], word_family: { noun: 'cessation' }, collocations: ['cease to exist', 'without cease'], example_sentence: 'The rain did not cease until the creek had risen over the crossing.', edutest_frequency: 3, writing_value: 'Formal alternative to "stop".' },
  { word: 'clever', level: 1, category: 'Mind', chinese: '聪明的', definition: 'Quick to understand, invent, or notice.', synonyms: ['sharp', 'ingenious'], antonyms: ['dull', 'slow'], word_family: { noun: 'cleverness', adverb: 'cleverly' }, collocations: ['clever solution', 'too clever'], example_sentence: 'The clever solution used the leftover string instead of asking for new equipment.', edutest_frequency: 3, writing_value: 'Can praise or warn, depending on tone.' },
  { word: 'commence', level: 1, category: 'Action', chinese: '开始', definition: 'To begin, especially in a formal or planned way.', synonyms: ['begin', 'start'], antonyms: ['conclude', 'finish'], word_family: { noun: 'commencement' }, collocations: ['commence work', 'commence proceedings'], example_sentence: 'The examination will commence at nine, whether every pencil is sharp or not.', edutest_frequency: 4, writing_value: 'Formal register for instructions and reports.' },
  { word: 'compare', level: 1, category: 'Academic', chinese: '比较', definition: 'To examine two or more things to see how they are alike or different.', synonyms: ['contrast', 'liken'], antonyms: ['isolate', 'separate'], word_family: { noun: 'comparison', adjective: 'comparable' }, collocations: ['compare with', 'compare and contrast'], example_sentence: 'Compare the two openings and decide which one earns the reader’s trust faster.', edutest_frequency: 5, writing_value: 'Core exam verb.' },
  { word: 'complete', level: 1, category: 'Quality', chinese: '完整的；完成', definition: 'Whole, or finished with nothing important missing.', synonyms: ['entire', 'finished'], antonyms: ['incomplete', 'partial'], word_family: { noun: 'completion', adverb: 'completely' }, collocations: ['complete the task', 'complete silence'], example_sentence: 'A complete answer names the reason, not only the event.', edutest_frequency: 4, writing_value: 'Useful as adjective or verb.' },
  { word: 'consider', level: 1, category: 'Mind', chinese: '考虑', definition: 'To think about something carefully before judging it.', synonyms: ['weigh', 'contemplate'], antonyms: ['ignore', 'dismiss'], word_family: { noun: 'consideration', adjective: 'considerate' }, collocations: ['consider the evidence', 'seriously consider'], example_sentence: 'Consider the evidence before you decide that the narrator is cruel.', edutest_frequency: 5, writing_value: 'Signals reasoned judgement.' },
  { word: 'courage', level: 1, category: 'Character', chinese: '勇气', definition: 'The quality of facing fear, pain, or difficulty with resolve.', synonyms: ['bravery', 'valour'], antonyms: ['cowardice', 'fear'], word_family: { adjective: 'courageous', adverb: 'courageously' }, collocations: ['have the courage', 'moral courage'], example_sentence: 'It took courage to admit that the winning idea had not been his.', edutest_frequency: 4, writing_value: 'Stronger than "being brave" in character essays.' },
  { word: 'curious', level: 1, category: 'Mind', chinese: '好奇的', definition: 'Eager to know or learn; unusual enough to attract attention.', synonyms: ['inquisitive', 'interested'], antonyms: ['indifferent', 'uninterested'], word_family: { noun: 'curiosity', adverb: 'curiously' }, collocations: ['curious about', 'curious fact'], example_sentence: 'A curious student asks why the writer chose that title, not only what it means.', edutest_frequency: 4, writing_value: 'Positive academic trait word.' },
  { word: 'decline', level: 1, category: 'Action', chinese: '拒绝；下降', definition: 'To refuse politely, or to become smaller or weaker.', synonyms: ['refuse', 'decrease'], antonyms: ['accept', 'increase'], word_family: { adjective: 'declining' }, collocations: ['decline an offer', 'sharp decline'], example_sentence: 'He chose to decline the easier class even though the harder one looked intimidating.', edutest_frequency: 4, writing_value: 'Two meanings; context decides.' },
  { word: 'definite', level: 1, category: 'Quality', chinese: '明确的', definition: 'Clear and unlikely to change; certain.', synonyms: ['certain', 'clear-cut'], antonyms: ['vague', 'uncertain'], word_family: { adverb: 'definitely', noun: 'definition' }, collocations: ['definite answer', 'definite plan'], example_sentence: 'The notice gave a definite time, so nobody could pretend to be confused.', edutest_frequency: 4, writing_value: 'Avoids the sloppy "definitely" habit when an adjective is needed.' },
  { word: 'delicate', level: 1, category: 'Quality', chinese: '脆弱的；微妙的', definition: 'Easily damaged, or requiring sensitive handling.', synonyms: ['fragile', 'sensitive'], antonyms: ['robust', 'coarse'], word_family: { noun: 'delicacy', adverb: 'delicately' }, collocations: ['delicate situation', 'delicate fabric'], example_sentence: 'It was a delicate situation: telling the truth would hurt someone who had tried to help.', edutest_frequency: 3, writing_value: 'Good for social and physical description.' },
  { word: 'demonstrate', level: 1, category: 'Academic', chinese: '证明；示范', definition: 'To show clearly by evidence, action, or example.', synonyms: ['show', 'prove'], antonyms: ['conceal', 'disprove'], word_family: { noun: 'demonstration', adjective: 'demonstrative' }, collocations: ['demonstrate understanding', 'demonstrate a method'], example_sentence: 'The diagram must demonstrate the process, not merely decorate the page.', edutest_frequency: 5, writing_value: 'High-value exam verb.' },
  { word: 'dense', level: 1, category: 'Description', chinese: '密集的', definition: 'Packed closely together; difficult to see through or to understand.', synonyms: ['thick', 'compact'], antonyms: ['sparse', 'thin'], word_family: { noun: 'density', adverb: 'densely' }, collocations: ['dense forest', 'dense fog'], example_sentence: 'A dense paragraph can hide the main idea from a hurried reader.', edutest_frequency: 3, writing_value: 'Works for landscape and writing style.' },
  { word: 'depend', level: 1, category: 'Relation', chinese: '依赖', definition: 'To need someone or something for support or success.', synonyms: ['rely', 'count on'], antonyms: ['independence'], word_family: { noun: 'dependence', adjective: 'dependable' }, collocations: ['depend on', 'dependable friend'], example_sentence: 'The experiment’s result would depend on whether they measured the water at the same time each day.', edutest_frequency: 4, writing_value: 'Foundation for "independent" contrast.' },
  { word: 'describe', level: 1, category: 'Communication', chinese: '描述', definition: 'To say what someone or something is like, using precise detail.', synonyms: ['portray', 'depict'], antonyms: ['omit', 'ignore'], word_family: { noun: 'description', adjective: 'descriptive' }, collocations: ['describe in detail', 'vividly describe'], example_sentence: 'Do not just name the setting; describe the heat that made the oval shimmer.', edutest_frequency: 5, writing_value: 'Core writing instruction word.' },
  { word: 'deserve', level: 1, category: 'Judgement', chinese: '应得', definition: 'To have earned a particular treatment or result.', synonyms: ['merit', 'earn'], antonyms: ['forfeit'], word_family: { adjective: 'deserving' }, collocations: ['deserve credit', 'deserve a chance'], example_sentence: 'A rushed paragraph does not deserve the same mark as a careful one.', edutest_frequency: 3, writing_value: 'Useful in moral judgements.' },
  { word: 'determine', level: 1, category: 'Mind', chinese: '确定；决心', definition: 'To decide firmly, or to find out the facts.', synonyms: ['decide', 'establish'], antonyms: ['waver', 'guess'], word_family: { noun: 'determination', adjective: 'determined' }, collocations: ['determine the cause', 'determined to succeed'], example_sentence: 'They had to determine whether the stain was rust or blood before leaping to a story.', edutest_frequency: 5, writing_value: 'Academic and character uses.' },
  { word: 'device', level: 1, category: 'Object', chinese: '装置；手法', definition: 'A tool or machine, or a method used to achieve an effect.', synonyms: ['gadget', 'technique'], antonyms: [], word_family: {}, collocations: ['literary device', 'safety device'], example_sentence: 'Repetition is a literary device the writer uses to make the warning unforgettable.', edutest_frequency: 4, writing_value: 'Key for language-analysis questions.' },
  { word: 'diligent', level: 1, category: 'Character', chinese: '勤奋的', definition: 'Working carefully and steadily, with proper attention.', synonyms: ['hardworking', 'industrious'], antonyms: ['lazy', 'careless'], word_family: { noun: 'diligence', adverb: 'diligently' }, collocations: ['diligent student', 'diligent research'], example_sentence: 'Diligent checking caught the reversed digits before the answer was submitted.', edutest_frequency: 4, writing_value: 'Scholarship-report vocabulary.' },
  { word: 'distinct', level: 1, category: 'Quality', chinese: '明显不同的', definition: 'Clearly different or easy to recognise separately.', synonyms: ['clear', 'separate'], antonyms: ['indistinct', 'blurred'], word_family: { noun: 'distinction', adverb: 'distinctly' }, collocations: ['distinct difference', 'distinct voice'], example_sentence: 'Each witness gave a distinct version of the same five minutes.', edutest_frequency: 4, writing_value: 'Helps comparison paragraphs.' },
  { word: 'eager', level: 1, category: 'Emotion', chinese: '热切的', definition: 'Wanting to do or have something very much.', synonyms: ['keen', 'enthusiastic'], antonyms: ['reluctant', 'unwilling'], word_family: { noun: 'eagerness', adverb: 'eagerly' }, collocations: ['eager to learn', 'eager crowd'], example_sentence: 'He was eager to begin, yet he still waited for the instruction.', edutest_frequency: 4, writing_value: 'Antonym pair with reluctant.' },
  { word: 'enormous', level: 1, category: 'Size', chinese: '巨大的', definition: 'Extremely large in size, amount, or importance.', synonyms: ['huge', 'immense'], antonyms: ['tiny', 'minute'], word_family: { noun: 'enormity', adverb: 'enormously' }, collocations: ['enormous effort', 'enormous difference'], example_sentence: 'An enormous effort went into a speech that lasted only four minutes.', edutest_frequency: 3, writing_value: 'Upgrade from "very big".' },
  { word: 'essential', level: 1, category: 'Academic', chinese: '必要的', definition: 'Absolutely necessary; of the greatest importance.', synonyms: ['vital', 'necessary'], antonyms: ['optional', 'unnecessary'], word_family: { noun: 'essence', adverb: 'essentially' }, collocations: ['essential information', 'essential skill'], example_sentence: 'It is essential to read the question words before you start writing.', edutest_frequency: 5, writing_value: 'High-frequency academic adjective.' },
  { word: 'evident', level: 1, category: 'Observation', chinese: '明显的', definition: 'Easy to see or understand; obvious from the facts.', synonyms: ['obvious', 'clear'], antonyms: ['unclear', 'doubtful'], word_family: { noun: 'evidence', adverb: 'evidently' }, collocations: ['evident from', 'plainly evident'], example_sentence: 'His disappointment was evident even though he congratulated the winner.', edutest_frequency: 5, writing_value: 'Links to "evidence" in essays.' },
  { word: 'familiar', level: 1, category: 'Experience', chinese: '熟悉的', definition: 'Well known because it has been seen or experienced before.', synonyms: ['known', 'recognisable'], antonyms: ['unfamiliar', 'strange'], word_family: { noun: 'familiarity', verb: 'familiarise' }, collocations: ['familiar with', 'familiar face'], example_sentence: 'The street was familiar, yet the locked gate made it feel like another town.', edutest_frequency: 3, writing_value: 'Good for setting and contrast.' },
  { word: 'frequent', level: 1, category: 'Time', chinese: '频繁的', definition: 'Happening often.', synonyms: ['regular', 'repeated'], antonyms: ['rare', 'occasional'], word_family: { noun: 'frequency', adverb: 'frequently' }, collocations: ['frequent visitor', 'frequent delays'], example_sentence: 'Frequent rereading is not a weakness; it is how difficult sentences give up their meaning.', edutest_frequency: 4, writing_value: 'Pairs with "rarely" in tone questions.' },
  { word: 'generous', level: 1, category: 'Character', chinese: '慷慨的', definition: 'Willing to give more than is necessary or expected.', synonyms: ['kind', 'magnanimous'], antonyms: ['selfish', 'mean'], word_family: { noun: 'generosity', adverb: 'generously' }, collocations: ['generous offer', 'generous praise'], example_sentence: 'A generous teammate passed the last easy question to the student who needed the practice.', edutest_frequency: 3, writing_value: 'Character description staple.' },
  { word: 'gradual', level: 1, category: 'Change', chinese: '逐渐的', definition: 'Happening slowly, in small stages.', synonyms: ['steady', 'progressive'], antonyms: ['sudden', 'abrupt'], word_family: { adverb: 'gradually' }, collocations: ['gradual change', 'gradual improvement'], example_sentence: 'Improvement in vocabulary is gradual; one precise word a day still changes a page.', edutest_frequency: 3, writing_value: 'Useful for process and growth.' },
  { word: 'honest', level: 1, category: 'Character', chinese: '诚实的', definition: 'Telling the truth and refusing to cheat or pretend.', synonyms: ['truthful', 'frank'], antonyms: ['dishonest', 'deceitful'], word_family: { noun: 'honesty', adverb: 'honestly' }, collocations: ['honest mistake', 'honest opinion'], example_sentence: 'An honest account included the part that made him look careless.', edutest_frequency: 4, writing_value: 'Moral centre of many narratives.' },
  { word: 'identify', level: 1, category: 'Academic', chinese: '识别', definition: 'To recognise and name someone or something correctly.', synonyms: ['recognise', 'pinpoint'], antonyms: ['overlook', 'misname'], word_family: { noun: 'identity', adjective: 'identifiable' }, collocations: ['identify the cause', 'identify with'], example_sentence: 'First identify the question type; then choose a method.', edutest_frequency: 5, writing_value: 'Exam instruction verb.' },
  { word: 'imagine', level: 1, category: 'Mind', chinese: '想象', definition: 'To form a picture or idea in the mind.', synonyms: ['picture', 'envision'], antonyms: ['witness'], word_family: { noun: 'imagination', adjective: 'imaginative' }, collocations: ['imagine a scene', 'hard to imagine'], example_sentence: 'Imagine the hall at 8:55: bags at the wall, nobody talking above a whisper.', edutest_frequency: 3, writing_value: 'Opens descriptive writing.' },
  { word: 'improve', level: 1, category: 'Change', chinese: '改进', definition: 'To make or become better.', synonyms: ['enhance', 'strengthen'], antonyms: ['worsen', 'decline'], word_family: { noun: 'improvement', adjective: 'improved' }, collocations: ['improve a draft', 'show improvement'], example_sentence: 'He did not replace the paragraph; he improved the verbs until the scene moved.', edutest_frequency: 4, writing_value: 'Process word for editing.' },
  { word: 'include', level: 1, category: 'Academic', chinese: '包括', definition: 'To make something part of a larger whole.', synonyms: ['contain', 'incorporate'], antonyms: ['exclude', 'omit'], word_family: { noun: 'inclusion', adjective: 'inclusive' }, collocations: ['include details', 'include evidence'], example_sentence: 'A strong paragraph must include evidence, not only opinion.', edutest_frequency: 4, writing_value: 'Pairs with "omit" in editing.' },
  { word: 'independent', level: 1, category: 'Character', chinese: '独立的', definition: 'Able to think or act without needing to be controlled.', synonyms: ['self-reliant', 'autonomous'], antonyms: ['dependent', 'reliant'], word_family: { noun: 'independence', adverb: 'independently' }, collocations: ['independent school', 'independent thought'], example_sentence: 'Independent thought is welcome; copying a classmate’s opening is not.', edutest_frequency: 5, writing_value: 'Australian scholarship context word.' },
  { word: 'indicate', level: 1, category: 'Academic', chinese: '表明', definition: 'To show or point to a fact, often without stating it directly.', synonyms: ['show', 'suggest'], antonyms: ['conceal', 'hide'], word_family: { noun: 'indication', adjective: 'indicative' }, collocations: ['indicate that', 'clear indication'], example_sentence: 'The final sentence indicates that the narrator has changed his mind.', edutest_frequency: 5, writing_value: 'Inference verb.' },
  { word: 'intend', level: 1, category: 'Mind', chinese: '打算', definition: 'To have a plan or purpose in mind.', synonyms: ['mean', 'plan'], antonyms: ['unintended'], word_family: { noun: 'intention', adjective: 'intentional' }, collocations: ['intend to', 'original intention'], example_sentence: 'The writer may intend humour, even if the character feels miserable.', edutest_frequency: 4, writing_value: 'Author-purpose vocabulary.' },
  { word: 'journey', level: 1, category: 'Adventure', chinese: '旅程', definition: 'An act of travelling from one place to another, or a long process of change.', synonyms: ['voyage', 'expedition'], antonyms: ['stay'], word_family: { verb: 'journey' }, collocations: ['long journey', 'journey of discovery'], example_sentence: 'The journey inland taught them more than the first glossy brochure had promised.', edutest_frequency: 3, writing_value: 'Literal and metaphorical uses.' },
  { word: 'likely', level: 1, category: 'Judgement', chinese: '可能的', definition: 'Probable; reasonably expected to happen or be true.', synonyms: ['probable', 'expected'], antonyms: ['unlikely', 'improbable'], word_family: { noun: 'likelihood' }, collocations: ['likely to', 'most likely'], example_sentence: 'The thief is more likely a student with a key than a stranger from the street.', edutest_frequency: 5, writing_value: 'Inference wording.' },
  { word: 'magnificent', level: 1, category: 'Description', chinese: '壮丽的', definition: 'Extremely impressive or beautiful.', synonyms: ['splendid', 'grand'], antonyms: ['ordinary', 'poor'], word_family: { noun: 'magnificence', adverb: 'magnificently' }, collocations: ['magnificent view', 'magnificent effort'], example_sentence: 'The hall was not magnificent, but the stained glass still caught the morning.', edutest_frequency: 3, writing_value: 'Upgrade from "amazing".' },
  { word: 'necessary', level: 1, category: 'Academic', chinese: '必要的', definition: 'Needed in order for something to happen or be complete.', synonyms: ['required', 'essential'], antonyms: ['unnecessary', 'optional'], word_family: { noun: 'necessity', adverb: 'necessarily' }, collocations: ['if necessary', 'necessary step'], example_sentence: 'It is not necessary to use a long word when a short exact one will do.', edutest_frequency: 4, writing_value: 'Logic and instruction word.' },
  { word: 'obvious', level: 1, category: 'Observation', chinese: '显而易见的', definition: 'Easy for anyone to see or understand.', synonyms: ['clear', 'plain'], antonyms: ['subtle', 'hidden'], word_family: { adverb: 'obviously', noun: 'obviousness' }, collocations: ['obvious reason', 'stating the obvious'], example_sentence: 'The obvious answer was a trap; the passage rewarded a second reading.', edutest_frequency: 4, writing_value: 'Often used ironically in exams.' },
  { word: 'ordinary', level: 1, category: 'Description', chinese: '普通的', definition: 'Normal; not special, extreme, or unusual.', synonyms: ['usual', 'everyday'], antonyms: ['extraordinary', 'remarkable'], word_family: { adverb: 'ordinarily' }, collocations: ['ordinary life', 'ordinary day'], example_sentence: 'The story begins on an ordinary Tuesday, which makes the later choice more striking.', edutest_frequency: 4, writing_value: 'Contrast word for narrative.' },
  { word: 'particular', level: 1, category: 'Precision', chinese: '特定的', definition: 'Used to single out one thing from others; specific.', synonyms: ['specific', 'certain'], antonyms: ['general', 'vague'], word_family: { adverb: 'particularly', noun: 'particularity' }, collocations: ['in particular', 'particular detail'], example_sentence: 'Pay particular attention to words in quotation marks.', edutest_frequency: 5, writing_value: 'Precision marker.' },
  { word: 'patient', level: 1, category: 'Character', chinese: '有耐心的', definition: 'Able to wait or keep trying without becoming angry.', synonyms: ['forbearing', 'calm'], antonyms: ['impatient', 'restless'], word_family: { noun: 'patience', adverb: 'patiently' }, collocations: ['patient explanation', 'lose patience'], example_sentence: 'A patient rereading found the pronoun that the first reading had skipped.', edutest_frequency: 3, writing_value: 'Character and study-habit word.' },
  { word: 'peculiar', level: 1, category: 'Description', chinese: '奇特的', definition: 'Strange, unusual, or belonging to one particular person or place.', synonyms: ['odd', 'distinctive'], antonyms: ['ordinary', 'typical'], word_family: { noun: 'peculiarity', adverb: 'peculiarly' }, collocations: ['peculiar habit', 'peculiar to'], example_sentence: 'There was a peculiar smell of varnish in a room that should have been unused.', edutest_frequency: 3, writing_value: 'Atmosphere and mystery.' },
  { word: 'pleasant', level: 1, category: 'Description', chinese: '令人愉快的', definition: 'Enjoyable, friendly, or giving a sense of ease.', synonyms: ['agreeable', 'enjoyable'], antonyms: ['unpleasant', 'harsh'], word_family: { adverb: 'pleasantly', noun: 'pleasantness' }, collocations: ['pleasant surprise', 'pleasant manner'], example_sentence: 'The teacher’s pleasant manner did not hide how strict the marking would be.', edutest_frequency: 3, writing_value: 'Tone word; can be ironic.' },
  { word: 'prevent', level: 1, category: 'Action', chinese: '阻止', definition: 'To stop something from happening or someone from doing something.', synonyms: ['stop', 'avert'], antonyms: ['allow', 'cause'], word_family: { noun: 'prevention', adjective: 'preventable' }, collocations: ['prevent an accident', 'prevent from'], example_sentence: 'A clear title can prevent the reader from misunderstanding the argument.', edutest_frequency: 4, writing_value: 'Cause-and-effect verb.' },
  { word: 'purpose', level: 1, category: 'Academic', chinese: '目的', definition: 'The reason something is done or created.', synonyms: ['aim', 'intention'], antonyms: ['aimlessness'], word_family: { adjective: 'purposeful', adverb: 'purposefully' }, collocations: ['main purpose', 'purpose of'], example_sentence: 'The purpose of the second paragraph is to undermine the first impression.', edutest_frequency: 5, writing_value: 'Author-purpose questions.' },
  { word: 'rapid', level: 1, category: 'Change', chinese: '迅速的', definition: 'Happening very quickly.', synonyms: ['swift', 'fast'], antonyms: ['slow', 'gradual'], word_family: { adverb: 'rapidly', noun: 'rapidity' }, collocations: ['rapid change', 'rapid response'], example_sentence: 'Rapid guessing is how easy marks disappear.', edutest_frequency: 3, writing_value: 'Upgrade from "quick".' },
  { word: 'recent', level: 1, category: 'Time', chinese: '最近的', definition: 'Having happened or been made not long ago.', synonyms: ['new', 'late'], antonyms: ['old', 'former'], word_family: { adverb: 'recently', noun: 'recency' }, collocations: ['recent study', 'in recent years'], example_sentence: 'A recent change to the timetable had left the hall strangely empty.', edutest_frequency: 3, writing_value: 'Report and news register.' },
  { word: 'require', level: 1, category: 'Academic', chinese: '需要', definition: 'To need something as necessary.', synonyms: ['need', 'demand'], antonyms: ['forgo'], word_family: { noun: 'requirement', adjective: 'required' }, collocations: ['require attention', 'required reading'], example_sentence: 'The question does not require a story; it requires a reason.', edutest_frequency: 5, writing_value: 'Instruction verb.' },
  { word: 'similar', level: 1, category: 'Relation', chinese: '相似的', definition: 'Almost the same, but not identical.', synonyms: ['alike', 'comparable'], antonyms: ['different', 'unlike'], word_family: { noun: 'similarity', adverb: 'similarly' }, collocations: ['similar to', 'similar pattern'], example_sentence: 'The two endings are similar, yet only one feels earned.', edutest_frequency: 5, writing_value: 'Compare/contrast essays.' },
  { word: 'sudden', level: 1, category: 'Change', chinese: '突然的', definition: 'Happening quickly and without warning.', synonyms: ['abrupt', 'unexpected'], antonyms: ['gradual', 'expected'], word_family: { adverb: 'suddenly', noun: 'suddenness' }, collocations: ['sudden change', 'sudden silence'], example_sentence: 'A sudden silence in the classroom is often more alarming than noise.', edutest_frequency: 3, writing_value: 'Narrative pacing.' },
  { word: 'suggest', level: 1, category: 'Academic', chinese: '暗示；建议', definition: 'To put forward an idea, or to hint that something is true.', synonyms: ['imply', 'propose'], antonyms: ['state', 'deny'], word_family: { noun: 'suggestion', adjective: 'suggestive' }, collocations: ['suggest that', 'evidence suggests'], example_sentence: 'The final image suggests regret without naming it.', edutest_frequency: 5, writing_value: 'Inference verb.' },
  { word: 'thorough', level: 1, category: 'Quality', chinese: '彻底的', definition: 'Complete and careful, with nothing important missed.', synonyms: ['careful', 'exhaustive'], antonyms: ['careless', 'cursory'], word_family: { adverb: 'thoroughly', noun: 'thoroughness' }, collocations: ['thorough check', 'thorough understanding'], example_sentence: 'A thorough check of the options revealed that two answers were half-true.', edutest_frequency: 4, writing_value: 'Study-habit and marking word.' },
  { word: 'unusual', level: 1, category: 'Description', chinese: '不寻常的', definition: 'Not common or ordinary; surprising because it is different.', synonyms: ['uncommon', 'rare'], antonyms: ['usual', 'typical'], word_family: { adverb: 'unusually' }, collocations: ['unusual request', 'highly unusual'], example_sentence: 'It was unusual for the captain to miss training without a message.', edutest_frequency: 3, writing_value: 'Flags significance in a passage.' },
  { word: 'valuable', level: 1, category: 'Judgement', chinese: '有价值的', definition: 'Worth a great deal of money, time, or attention.', synonyms: ['precious', 'worthwhile'], antonyms: ['worthless', 'useless'], word_family: { noun: 'value', verb: 'value' }, collocations: ['valuable lesson', 'valuable information'], example_sentence: 'The most valuable lesson was not the formula but the habit of checking units.', edutest_frequency: 3, writing_value: 'Evaluation word.' },
  { word: 'various', level: 1, category: 'Quantity', chinese: '各种各样的', definition: 'Several different kinds.', synonyms: ['several', 'assorted'], antonyms: ['single', 'uniform'], word_family: { noun: 'variety', adverb: 'variously' }, collocations: ['various reasons', 'various sources'], example_sentence: 'The same event was described for various reasons, and not all of them were honest.', edutest_frequency: 4, writing_value: 'Upgrade from "different things".' },
];

export const SEED_ROWS: SeedRow[] = [...L1, ...L2, ...L3, ...L4, ...L5];

export function expandSeed(rows: SeedRow[]): VocabularyEntry[] {
  return rows.map((row, index) => ({
    id: `VOC${String(index + 1).padStart(4, '0')}`,
    ...row,
  }));
}
