import type { VocabularyLevel, WordFamily } from '../types';

type SeedRow = {
  word: string;
  level: VocabularyLevel;
  category: string;
  chinese: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  word_family: WordFamily;
  collocations: string[];
  example_sentence: string;
  edutest_frequency: number;
  writing_value: string;
};

export const L3: SeedRow[] = [
  { word: 'bleak', level: 3, category: 'Atmosphere', chinese: '荒凉的', definition: 'Cold, empty, and without comfort or hope.', synonyms: ['desolate', 'grim'], antonyms: ['cheerful', 'promising'], word_family: { noun: 'bleakness', adverb: 'bleakly' }, collocations: ['bleak landscape', 'bleak outlook'], example_sentence: 'The paddock looked bleak after the fire, yet green shoots had already begun.', edutest_frequency: 4, writing_value: 'Setting and mood.' },
  { word: 'chaotic', level: 3, category: 'Atmosphere', chinese: '混乱的', definition: 'In a state of complete disorder and confusion.', synonyms: ['disordered', 'tumultuous'], antonyms: ['orderly', 'organised'], word_family: { noun: 'chaos', adverb: 'chaotically' }, collocations: ['chaotic scene', 'chaotic morning'], example_sentence: 'The chaotic morning still produced a quiet, well-ruled exam paper.', edutest_frequency: 3, writing_value: 'Contrast word.' },
  { word: 'colossal', level: 3, category: 'Size', chinese: '庞大的', definition: 'Extremely large; astonishing in scale.', synonyms: ['huge', 'gigantic'], antonyms: ['tiny', 'slight'], word_family: { noun: 'colossus' }, collocations: ['colossal mistake', 'colossal effort'], example_sentence: 'Losing five marks to sloppy reading felt like a colossal mistake.', edutest_frequency: 3, writing_value: 'Emphasis without slang.' },
  { word: 'concealed', level: 3, category: 'Mystery', chinese: '隐藏的', definition: 'Hidden so that it cannot easily be seen or known.', synonyms: ['hidden', 'masked'], antonyms: ['exposed', 'revealed'], word_family: { verb: 'conceal', noun: 'concealment' }, collocations: ['concealed door', 'carefully concealed'], example_sentence: 'A carefully concealed clue sat in the third paragraph, dressed as a weather remark.', edutest_frequency: 4, writing_value: 'Mystery and inference.' },
  { word: 'conspicuous', level: 3, category: 'Observation', chinese: '显眼的', definition: 'Very easy to notice; attracting attention.', synonyms: ['noticeable', 'obvious'], antonyms: ['inconspicuous', 'hidden'], word_family: { adverb: 'conspicuously', noun: 'conspicuousness' }, collocations: ['conspicuous absence', 'conspicuous error'], example_sentence: 'His conspicuous absence from rehearsal was discussed more than the play.', edutest_frequency: 3, writing_value: 'Precise noticing.' },
  { word: 'cunning', level: 3, category: 'Character', chinese: '狡猾的', definition: 'Skilful at achieving goals by clever, sometimes dishonest, means.', synonyms: ['crafty', 'shrewd'], antonyms: ['naive', 'ingenuous'], word_family: { noun: 'cunning' }, collocations: ['cunning plan', 'cunning look'], example_sentence: 'The cunning plan worked until someone asked for the original source.', edutest_frequency: 3, writing_value: 'Ambiguous trait.' },
  { word: 'dazzling', level: 3, category: 'Description', chinese: '耀眼的', definition: 'Extremely bright or impressive.', synonyms: ['brilliant', 'radiant'], antonyms: ['dull', 'dim'], word_family: { verb: 'dazzle', noun: 'dazzle' }, collocations: ['dazzling light', 'dazzling performance'], example_sentence: 'A dazzling performance can still hide a thin argument.', edutest_frequency: 2, writing_value: 'Sensory and evaluative.' },
  { word: 'deliberate', level: 3, category: 'Mind', chinese: '故意的；审慎的', definition: 'Done on purpose, or slow and careful in thought.', synonyms: ['intentional', 'measured'], antonyms: ['accidental', 'hasty'], word_family: { adverb: 'deliberately', noun: 'deliberation' }, collocations: ['deliberate choice', 'deliberate pace'], example_sentence: 'The writer’s repetition is deliberate; treat it as a signal, not a mistake.', edutest_frequency: 5, writing_value: 'Author-craft word.' },
  { word: 'desolate', level: 3, category: 'Atmosphere', chinese: '荒芜的', definition: 'Empty, lonely, and without life or comfort.', synonyms: ['bleak', 'abandoned'], antonyms: ['populated', 'cheerful'], word_family: { noun: 'desolation' }, collocations: ['desolate landscape', 'desolate feeling'], example_sentence: 'The desolate station at dusk made even a delayed train feel like company.', edutest_frequency: 4, writing_value: 'High-value setting word.' },
  { word: 'discreet', level: 3, category: 'Character', chinese: '谨慎的', definition: 'Careful not to attract attention or cause embarrassment.', synonyms: ['tactful', 'prudent'], antonyms: ['indiscreet', 'blunt'], word_family: { noun: 'discretion', adverb: 'discreetly' }, collocations: ['discreet question', 'discreet silence'], example_sentence: 'A discreet question saved the friend from public correction.', edutest_frequency: 3, writing_value: 'Not the same as "discrete".' },
  { word: 'eerie', level: 3, category: 'Atmosphere', chinese: '怪异阴森的', definition: 'Strange in a way that makes one uneasy.', synonyms: ['uncanny', 'spooky'], antonyms: ['ordinary', 'reassuring'], word_family: { adverb: 'eerily' }, collocations: ['eerie silence', 'eerie light'], example_sentence: 'An eerie silence in a usually noisy corridor is a story beginning.', edutest_frequency: 3, writing_value: 'Mystery atmosphere.' },
  { word: 'elaborate', level: 3, category: 'Quality', chinese: '详尽的', definition: 'Detailed and complicated; to add more detail.', synonyms: ['intricate', 'detailed'], antonyms: ['simple', 'plain'], word_family: { noun: 'elaboration', adverb: 'elaborately' }, collocations: ['elaborate plan', 'elaborate on'], example_sentence: 'Do not elaborate on a point you cannot support.', edutest_frequency: 4, writing_value: 'Adjective and verb.' },
  { word: 'eloquent', level: 3, category: 'Communication', chinese: '雄辩的', definition: 'Fluent, graceful, and persuasive in speech or writing.', synonyms: ['articulate', 'expressive'], antonyms: ['inarticulate', 'clumsy'], word_family: { noun: 'eloquence', adverb: 'eloquently' }, collocations: ['eloquent speech', 'eloquent silence'], example_sentence: 'The most eloquent sentence in the piece was also the shortest.', edutest_frequency: 3, writing_value: 'Praise for style.' },
  { word: 'emphatic', level: 3, category: 'Communication', chinese: '强调的', definition: 'Expressed with force and clarity; leaving no doubt.', synonyms: ['forceful', 'insistent'], antonyms: ['hesitant', 'vague'], word_family: { noun: 'emphasis', verb: 'emphasise' }, collocations: ['emphatic denial', 'emphatic pause'], example_sentence: 'Her emphatic pause before "however" told the class to listen.', edutest_frequency: 3, writing_value: 'Tone and argument.' },
  { word: 'engulf', level: 3, category: 'Action', chinese: '吞没', definition: 'To surround and cover completely.', synonyms: ['swallow', 'overwhelm'], antonyms: ['release', 'recede'], word_family: { noun: 'engulfment' }, collocations: ['engulfed by smoke', 'engulfed in work'], example_sentence: 'Fog can engulf a coastal road faster than a driver expects.', edutest_frequency: 3, writing_value: 'Dramatic verb.' },
  { word: 'enigma', level: 3, category: 'Mystery', chinese: '谜', definition: 'A person, thing, or situation that is mysterious and hard to understand.', synonyms: ['mystery', 'puzzle'], antonyms: ['certainty', 'explanation'], word_family: { adjective: 'enigmatic' }, collocations: ['complete enigma', 'remains an enigma'], example_sentence: 'The missing page remained an enigma until someone checked the recycling bin.', edutest_frequency: 3, writing_value: 'Noun form of enigmatic.' },
  { word: 'enthral', level: 3, category: 'Response', chinese: '迷住', definition: 'To hold someone’s complete attention; to fascinate.', synonyms: ['captivate', 'fascinate'], antonyms: ['bore', 'repel'], word_family: { adjective: 'enthralling', noun: 'enthralment' }, collocations: ['enthral the audience', 'utterly enthralled'], example_sentence: 'The speaker did not shout; she enthralled the hall with one exact story.', edutest_frequency: 2, writing_value: 'Australian spelling.' },
  { word: 'evade', level: 3, category: 'Action', chinese: '逃避', definition: 'To escape or avoid, especially by cleverness or delay.', synonyms: ['avoid', 'dodge'], antonyms: ['face', 'confront'], word_family: { noun: 'evasion', adjective: 'evasive' }, collocations: ['evade a question', 'evade capture'], example_sentence: 'He tried to evade the question with a joke, which answered it anyway.', edutest_frequency: 4, writing_value: 'Character and interview tell.' },
  { word: 'exaggerate', level: 3, category: 'Communication', chinese: '夸大', definition: 'To make something seem larger, better, or worse than it is.', synonyms: ['overstate', 'inflate'], antonyms: ['understate', 'minimise'], word_family: { noun: 'exaggeration', adjective: 'exaggerated' }, collocations: ['exaggerate a claim', 'wildly exaggerate'], example_sentence: 'Scholarship writing loses marks when students exaggerate a small detail into a crisis.', edutest_frequency: 4, writing_value: 'Editing warning.' },
  { word: 'exasperate', level: 3, category: 'Emotion', chinese: '激怒', definition: 'To irritate someone intensely.', synonyms: ['infuriate', 'irritate'], antonyms: ['soothe', 'calm'], word_family: { noun: 'exasperation', adjective: 'exasperated' }, collocations: ['exasperate a teacher', 'exasperated sigh'], example_sentence: 'Repeating the same careless error will exasperate even a patient marker.', edutest_frequency: 3, writing_value: 'Stronger than "annoy".' },
  { word: 'exceptional', level: 3, category: 'Quality', chinese: '杰出的', definition: 'Unusually good, or unusual in a way that stands apart.', synonyms: ['outstanding', 'remarkable'], antonyms: ['ordinary', 'average'], word_family: { noun: 'exception', adverb: 'exceptionally' }, collocations: ['exceptional talent', 'exceptional case'], example_sentence: 'Exceptional work is often ordinary work repeated with unusual care.', edutest_frequency: 4, writing_value: 'Evaluation word — use sparingly.' },
  { word: 'explicit', level: 3, category: 'Academic', chinese: '明确的', definition: 'Stated clearly and in detail, leaving no room for confusion.', synonyms: ['clear', 'unambiguous'], antonyms: ['implicit', 'vague'], word_family: { adverb: 'explicitly', noun: 'explicitness' }, collocations: ['explicit instruction', 'make explicit'], example_sentence: 'The rule was explicit: no notes, no phones, no talking after papers are opened.', edutest_frequency: 5, writing_value: 'Pairs with implicit.' },
  { word: 'exquisite', level: 3, category: 'Description', chinese: '精美的', definition: 'Extremely beautiful, delicate, or finely made.', synonyms: ['fine', 'beautiful'], antonyms: ['crude', 'coarse'], word_family: { adverb: 'exquisitely' }, collocations: ['exquisite detail', 'exquisite care'], example_sentence: 'The map was drawn with exquisite care, including the creek that no longer existed.', edutest_frequency: 2, writing_value: 'Sensory precision.' },
  { word: 'extensive', level: 3, category: 'Quantity', chinese: '广泛的', definition: 'Covering a large area or a great amount.', synonyms: ['wide', 'far-reaching'], antonyms: ['limited', 'narrow'], word_family: { noun: 'extent', adverb: 'extensively' }, collocations: ['extensive research', 'extensive damage'], example_sentence: 'Extensive reading is not the same as careful reading.', edutest_frequency: 4, writing_value: 'Academic adjective.' },
  { word: 'feeble', level: 3, category: 'Quality', chinese: '虚弱的', definition: 'Weak in body, argument, or effect.', synonyms: ['weak', 'frail'], antonyms: ['strong', 'robust'], word_family: { noun: 'feebleness', adverb: 'feebly' }, collocations: ['feeble excuse', 'feeble attempt'], example_sentence: 'A feeble excuse is worse than a short honest one.', edutest_frequency: 3, writing_value: 'Judgement of quality.' },
  { word: 'fleeting', level: 3, category: 'Time', chinese: '短暂的', definition: 'Lasting for a very short time.', synonyms: ['brief', 'momentary'], antonyms: ['lasting', 'enduring'], word_family: { verb: 'fleet' }, collocations: ['fleeting moment', 'fleeting glance'], example_sentence: 'A fleeting glance at the options is how two similar answers trick you.', edutest_frequency: 3, writing_value: 'Time and attention.' },
  { word: 'formidable', level: 3, category: 'Quality', chinese: '强大可畏的', definition: 'Inspiring respect or fear because of size, difficulty, or strength.', synonyms: ['daunting', 'imposing'], antonyms: ['weak', 'unimpressive'], word_family: { adverb: 'formidably' }, collocations: ['formidable opponent', 'formidable task'], example_sentence: 'The paper looked formidable until he sorted the questions by type.', edutest_frequency: 4, writing_value: 'Challenge without panic.' },
  { word: 'fragile', level: 3, category: 'Quality', chinese: '易碎的', definition: 'Easily broken, damaged, or upset.', synonyms: ['delicate', 'breakable'], antonyms: ['sturdy', 'robust'], word_family: { noun: 'fragility' }, collocations: ['fragile truce', 'fragile object'], example_sentence: 'Their friendship was fragile after the rumour, and jokes did not repair it.', edutest_frequency: 3, writing_value: 'Physical and emotional.' },
  { word: 'grim', level: 3, category: 'Atmosphere', chinese: '严峻的', definition: 'Unpleasant, stern, or without hope.', synonyms: ['bleak', 'harsh'], antonyms: ['cheerful', 'bright'], word_family: { adverb: 'grimly', noun: 'grimness' }, collocations: ['grim news', 'grim expression'], example_sentence: 'The grim news from the river flats made the assembly unusually short.', edutest_frequency: 3, writing_value: 'Tone.' },
  { word: 'harsh', level: 3, category: 'Quality', chinese: '严厉的', definition: 'Unpleasantly severe, rough, or cruel.', synonyms: ['severe', 'stern'], antonyms: ['gentle', 'mild'], word_family: { noun: 'harshness', adverb: 'harshly' }, collocations: ['harsh criticism', 'harsh climate'], example_sentence: 'Harsh criticism can be accurate and still be badly timed.', edutest_frequency: 3, writing_value: 'Tone and climate.' },
  { word: 'hostile', level: 3, category: 'Atmosphere', chinese: '敌对的', definition: 'Unfriendly, opposing, or difficult to survive in.', synonyms: ['unfriendly', 'antagonistic'], antonyms: ['friendly', 'welcoming'], word_family: { noun: 'hostility', adverb: 'hostilely' }, collocations: ['hostile crowd', 'hostile environment'], example_sentence: 'A hostile silence can be louder than an argument.', edutest_frequency: 4, writing_value: 'Conflict setting.' },
  { word: 'immense', level: 3, category: 'Size', chinese: '巨大的', definition: 'Extremely large or great.', synonyms: ['vast', 'enormous'], antonyms: ['tiny', 'slight'], word_family: { noun: 'immensity', adverb: 'immensely' }, collocations: ['immense pressure', 'immense relief'], example_sentence: 'Immense pressure does not excuse a dishonest shortcut.', edutest_frequency: 3, writing_value: 'Scale.' },
  { word: 'intricate', level: 3, category: 'Quality', chinese: '复杂精细的', definition: 'Having many small parts arranged in a complicated way.', synonyms: ['complex', 'elaborate'], antonyms: ['simple', 'plain'], word_family: { noun: 'intricacy', adverb: 'intricately' }, collocations: ['intricate pattern', 'intricate plot'], example_sentence: 'An intricate plot rewards the reader who tracks who knew what, and when.', edutest_frequency: 4, writing_value: 'Craft and setting.' },
  { word: 'isolated', level: 3, category: 'Setting', chinese: '孤立的', definition: 'Far from others; separated from help, company, or connection.', synonyms: ['remote', 'cut off'], antonyms: ['connected', 'central'], word_family: { noun: 'isolation', verb: 'isolate' }, collocations: ['isolated town', 'feel isolated'], example_sentence: 'The isolated homestead had a radio, a dog, and a long list of jobs.', edutest_frequency: 3, writing_value: 'Australian setting word.' },
  { word: 'lavish', level: 3, category: 'Quality', chinese: '奢华的', definition: 'Rich, generous, or more expensive than necessary.', synonyms: ['luxurious', 'extravagant'], antonyms: ['modest', 'spare'], word_family: { noun: 'lavishness', adverb: 'lavishly' }, collocations: ['lavish praise', 'lavish display'], example_sentence: 'Lavish praise for a first draft can stop a writer from making it better.', edutest_frequency: 2, writing_value: 'Tone of excess.' },
  { word: 'majestic', level: 3, category: 'Description', chinese: '雄伟的', definition: 'Having impressive beauty, dignity, or power.', synonyms: ['grand', 'noble'], antonyms: ['humble', 'ordinary'], word_family: { noun: 'majesty', adverb: 'majestically' }, collocations: ['majestic view', 'majestic silence'], example_sentence: 'The river gum looked majestic even with a split trunk.', edutest_frequency: 2, writing_value: 'Landscape register.' },
  { word: 'monotonous', level: 3, category: 'Quality', chinese: '单调的', definition: 'Dull because it does not change.', synonyms: ['tedious', 'repetitive'], antonyms: ['varied', 'lively'], word_family: { noun: 'monotony', adverb: 'monotonously' }, collocations: ['monotonous voice', 'monotonous routine'], example_sentence: 'A monotonous voice can turn a good argument into background noise.', edutest_frequency: 3, writing_value: 'Style criticism.' },
  { word: 'obscure', level: 3, category: 'Quality', chinese: '晦涩的', definition: 'Not well known, or not easy to understand.', synonyms: ['unclear', 'little-known'], antonyms: ['clear', 'famous'], word_family: { noun: 'obscurity', adverb: 'obscurely' }, collocations: ['obscure reference', 'remain obscure'], example_sentence: 'An obscure reference is not impressive if the reader cannot follow it.', edutest_frequency: 4, writing_value: 'Reading difficulty.' },
  { word: 'ominous', level: 3, category: 'Atmosphere', chinese: '不祥的', definition: 'Suggesting that something bad is coming.', synonyms: ['threatening', 'foreboding'], antonyms: ['promising', 'reassuring'], word_family: { noun: 'omen', adverb: 'ominously' }, collocations: ['ominous silence', 'ominous cloud'], example_sentence: 'An ominous quiet settled over the oval when the sky turned the colour of bruise.', edutest_frequency: 5, writing_value: 'Scholarship favourite mood word.' },
  { word: 'ornate', level: 3, category: 'Description', chinese: '华丽的', definition: 'Heavily decorated; using many details or fancy words.', synonyms: ['decorative', 'elaborate'], antonyms: ['plain', 'simple'], word_family: { adverb: 'ornately' }, collocations: ['ornate ceiling', 'ornate language'], example_sentence: 'Ornate language can hide the fact that nothing is being said.', edutest_frequency: 3, writing_value: 'Style judgement.' },
  { word: 'perpetual', level: 3, category: 'Time', chinese: '永久的', definition: 'Never ending, or seeming to continue without a break.', synonyms: ['endless', 'continual'], antonyms: ['temporary', 'brief'], word_family: { adverb: 'perpetually' }, collocations: ['perpetual motion', 'perpetual complaint'], example_sentence: 'A perpetual complaint becomes easier to ignore than a single precise one.', edutest_frequency: 3, writing_value: 'Duration.' },
  { word: 'precarious', level: 3, category: 'Quality', chinese: '不稳的', definition: 'Not securely held; likely to collapse or fail.', synonyms: ['unstable', 'insecure'], antonyms: ['secure', 'stable'], word_family: { adverb: 'precariously', noun: 'precariousness' }, collocations: ['precarious position', 'precarious balance'], example_sentence: 'His lead in the debate felt precarious after the last unexpected statistic.', edutest_frequency: 4, writing_value: 'Tension and risk.' },
  { word: 'primitive', level: 3, category: 'Quality', chinese: '原始的', definition: 'Belonging to an early stage; simple and undeveloped.', synonyms: ['basic', 'crude'], antonyms: ['advanced', 'sophisticated'], word_family: { noun: 'primitiveness' }, collocations: ['primitive tool', 'primitive method'], example_sentence: 'The method looked primitive, but it measured the creek more honestly than the app.', edutest_frequency: 3, writing_value: 'History and science.' },
  { word: 'profound', level: 3, category: 'Quality', chinese: '深刻的', definition: 'Very great or deep; showing serious understanding.', synonyms: ['deep', 'far-reaching'], antonyms: ['shallow', 'superficial'], word_family: { noun: 'profundity', adverb: 'profoundly' }, collocations: ['profound effect', 'profound question'], example_sentence: 'A profound question can be asked in ordinary words.', edutest_frequency: 5, writing_value: 'Evaluation of ideas.' },
  { word: 'radiant', level: 3, category: 'Description', chinese: '容光焕发的', definition: 'Shining brightly, or showing great joy.', synonyms: ['glowing', 'beaming'], antonyms: ['dull', 'gloomy'], word_family: { noun: 'radiance', verb: 'radiate' }, collocations: ['radiant smile', 'radiant light'], example_sentence: 'Her radiant smile lasted until she saw the one question she had hoped to avoid.', edutest_frequency: 2, writing_value: 'Visual emotion.' },
  { word: 'relentless', level: 3, category: 'Quality', chinese: '不懈的', definition: 'Not stopping or becoming less intense.', synonyms: ['persistent', 'unyielding'], antonyms: ['gentle', 'intermittent'], word_family: { adverb: 'relentlessly' }, collocations: ['relentless pressure', 'relentless heat'], example_sentence: 'Relentless practice is useful; relentless self-criticism is not.', edutest_frequency: 4, writing_value: 'Intensity.' },
  { word: 'remote', level: 3, category: 'Setting', chinese: '偏远的', definition: 'Far away in place, time, or likelihood.', synonyms: ['distant', 'isolated'], antonyms: ['nearby', 'likely'], word_family: { noun: 'remoteness' }, collocations: ['remote town', 'remote chance'], example_sentence: 'There was only a remote chance the ferry would wait.', edutest_frequency: 3, writing_value: 'Place and probability.' },
  { word: 'rustic', level: 3, category: 'Setting', chinese: '乡土的', definition: 'Simple and typical of the countryside.', synonyms: ['rural', 'pastoral'], antonyms: ['urban', 'sophisticated'], word_family: { noun: 'rusticity' }, collocations: ['rustic cabin', 'rustic charm'], example_sentence: 'The rustic hall had better acoustics than the new gym.', edutest_frequency: 2, writing_value: 'Setting colour.' },
  { word: 'savage', level: 3, category: 'Quality', chinese: '凶残的', definition: 'Fierce, violent, or extremely severe.', synonyms: ['brutal', 'ferocious'], antonyms: ['gentle', 'mild'], word_family: { noun: 'savagery', adverb: 'savagely' }, collocations: ['savage storm', 'savage criticism'], example_sentence: 'Savage criticism of a first attempt teaches people to hide their drafts.', edutest_frequency: 3, writing_value: 'Strong tone — use precisely.' },
  { word: 'serene', level: 3, category: 'Atmosphere', chinese: '宁静的', definition: 'Calm, peaceful, and untroubled.', synonyms: ['tranquil', 'peaceful'], antonyms: ['agitated', 'stormy'], word_family: { noun: 'serenity', adverb: 'serenely' }, collocations: ['serene lake', 'serene expression'], example_sentence: 'The lake looked serene, which is how deep water often lies.', edutest_frequency: 3, writing_value: 'Mood contrast.' },
  { word: 'sombre', level: 3, category: 'Atmosphere', chinese: '阴沉的', definition: 'Dark, serious, and lacking brightness or cheer.', synonyms: ['gloomy', 'solemn'], antonyms: ['bright', 'cheerful'], word_family: { adverb: 'sombrely' }, collocations: ['sombre mood', 'sombre news'], example_sentence: 'A sombre mood filled the classroom after the bushfire update.', edutest_frequency: 4, writing_value: 'Australian spelling of somber.' },
  { word: 'subtle', level: 3, category: 'Quality', chinese: '微妙的', definition: 'Not obvious; fine, delicate, or working in a quiet way.', synonyms: ['slight', 'understated'], antonyms: ['obvious', 'blatant'], word_family: { noun: 'subtlety', adverb: 'subtly' }, collocations: ['subtle hint', 'subtle difference'], example_sentence: 'The subtle difference between "imply" and "infer" is an exam gift if you know it.', edutest_frequency: 5, writing_value: 'Top comprehension word.' },
  { word: 'vast', level: 3, category: 'Size', chinese: '广阔的', definition: 'Extremely large in area, amount, or range.', synonyms: ['huge', 'immense'], antonyms: ['tiny', 'narrow'], word_family: { noun: 'vastness', adverb: 'vastly' }, collocations: ['vast distance', 'vast difference'], example_sentence: 'A vast difference in tone can hang on a single adjective.', edutest_frequency: 3, writing_value: 'Scale.' },
  { word: 'vivid', level: 3, category: 'Description', chinese: '生动的', definition: 'Producing strong, clear images or feelings.', synonyms: ['striking', 'graphic'], antonyms: ['dull', 'vague'], word_family: { adverb: 'vividly', noun: 'vividness' }, collocations: ['vivid description', 'vivid memory'], example_sentence: 'A vivid description of the hall is better than calling it "amazing".', edutest_frequency: 5, writing_value: 'Writing-quality word.' },
  { word: 'wearying', level: 3, category: 'Quality', chinese: '令人疲倦的', definition: 'Making someone tired through long effort or repetition.', synonyms: ['tiring', 'draining'], antonyms: ['refreshing', 'restorative'], word_family: { verb: 'weary', adjective: 'weary' }, collocations: ['wearying task', 'wearying heat'], example_sentence: 'The wearying heat made even simple addition feel like a negotiation.', edutest_frequency: 2, writing_value: 'Atmosphere through fatigue.' },
  { word: 'wretched', level: 3, category: 'Quality', chinese: '悲惨的', definition: 'Very unhappy, poor in quality, or deserving pity.', synonyms: ['miserable', 'pitiful'], antonyms: ['content', 'excellent'], word_family: { noun: 'wretchedness', adverb: 'wretchedly' }, collocations: ['wretched condition', 'feel wretched'], example_sentence: 'He felt wretched about the lie long before anyone discovered it.', edutest_frequency: 3, writing_value: 'Emotional intensity.' },
  { word: 'abrupt', level: 3, category: 'Change', chinese: '突然的', definition: 'Sudden and unexpected, often uncomfortably so.', synonyms: ['sudden', 'curt'], antonyms: ['gradual', 'gentle'], word_family: { adverb: 'abruptly', noun: 'abruptness' }, collocations: ['abrupt change', 'abrupt ending'], example_sentence: 'The story’s abrupt ending is a choice, not a mistake — say what it does to the reader.', edutest_frequency: 4, writing_value: 'Pacing and tone.' },
  { word: 'barren', level: 3, category: 'Setting', chinese: '贫瘠的', definition: 'Unable to produce life, growth, or useful result.', synonyms: ['infertile', 'empty'], antonyms: ['fertile', 'productive'], word_family: { noun: 'barrenness' }, collocations: ['barren land', 'barren argument'], example_sentence: 'A barren argument repeats a claim without adding a reason.', edutest_frequency: 3, writing_value: 'Literal and metaphorical.' },
  { word: 'crude', level: 3, category: 'Quality', chinese: '粗糙的', definition: 'Rough, simple, or lacking skill and refinement.', synonyms: ['rough', 'unrefined'], antonyms: ['refined', 'sophisticated'], word_family: { adverb: 'crudely', noun: 'crudeness' }, collocations: ['crude sketch', 'crude remark'], example_sentence: 'A crude first sketch is allowed; a crude insult is not.', edutest_frequency: 3, writing_value: 'Quality judgement.' },
];
