import type { VocabularyLevel, WordFamily } from '../types';

type SeedRow = {
  word: string;
  level: VocabularyLevel;
  category: string;
  chinese: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  word_family: WordFamily;
  collocations: string[];
  example_sentence: string;
  edutest_frequency: number;
  writing_value: string;
};

export const L2: SeedRow[] = [
  { word: 'affectionate', level: 2, category: 'Emotion', chinese: '亲切的', definition: 'Showing fondness or gentle care.', synonyms: ['loving', 'tender'], antonyms: ['cold', 'distant'], word_family: { noun: 'affection', adverb: 'affectionately' }, collocations: ['affectionate gesture', 'affectionate tone'], example_sentence: 'An affectionate note from his grandmother sat in the lunchbox like a secret.', edutest_frequency: 3, writing_value: 'Warm character detail.' },
  { word: 'aggressive', level: 2, category: 'Character', chinese: '好斗的', definition: 'Ready to attack, argue, or push forward forcefully.', synonyms: ['hostile', 'forceful'], antonyms: ['gentle', 'passive'], word_family: { noun: 'aggression', adverb: 'aggressively' }, collocations: ['aggressive behaviour', 'aggressive approach'], example_sentence: 'His aggressive tone made a fair argument sound like a threat.', edutest_frequency: 3, writing_value: 'Use when conflict is more than disagreement.' },
  { word: 'ambitious', level: 2, category: 'Character', chinese: '有抱负的', definition: 'Determined to achieve success or a demanding goal.', synonyms: ['aspiring', 'driven'], antonyms: ['unambitious', 'aimless'], word_family: { noun: 'ambition', adverb: 'ambitiously' }, collocations: ['ambitious plan', 'ambitious student'], example_sentence: 'An ambitious plan is admirable until it leaves no time for sleep or kindness.', edutest_frequency: 4, writing_value: 'Scholarship self-description word — use with balance.' },
  { word: 'apprehensive', level: 2, category: 'Emotion', chinese: '忧虑的', definition: 'Anxious that something unpleasant may happen.', synonyms: ['uneasy', 'worried'], antonyms: ['confident', 'assured'], word_family: { noun: 'apprehension' }, collocations: ['apprehensive about', 'apprehensive glance'], example_sentence: 'She was apprehensive about the oral, yet her notes were in perfect order.', edutest_frequency: 4, writing_value: 'Finer than "scared".' },
  { word: 'arrogant', level: 2, category: 'Character', chinese: '傲慢的', definition: 'Behaving as if superior to others and unwilling to listen.', synonyms: ['conceited', 'haughty'], antonyms: ['humble', 'modest'], word_family: { noun: 'arrogance', adverb: 'arrogantly' }, collocations: ['arrogant smile', 'arrogant assumption'], example_sentence: 'The arrogant assumption that nobody else had prepared made his error more public.', edutest_frequency: 4, writing_value: 'Classic antagonist trait.' },
  { word: 'ashamed', level: 2, category: 'Emotion', chinese: '羞愧的', definition: 'Feeling guilt or embarrassment about something done or left undone.', synonyms: ['embarrassed', 'guilty'], antonyms: ['proud', 'unashamed'], word_family: { noun: 'shame', adjective: 'shameful' }, collocations: ['ashamed of', 'deeply ashamed'], example_sentence: 'He was ashamed of the copied sentence the moment the teacher paused beside his desk.', edutest_frequency: 3, writing_value: 'Moral turning point.' },
  { word: 'bitter', level: 2, category: 'Emotion', chinese: '苦涩的；怨恨的', definition: 'Angry and hurt because of unfairness or disappointment.', synonyms: ['resentful', 'acerbic'], antonyms: ['forgiving', 'sweet'], word_family: { noun: 'bitterness', adverb: 'bitterly' }, collocations: ['bitter disappointment', 'bitter argument'], example_sentence: 'A bitter comment can be true and still be the wrong thing to say.', edutest_frequency: 3, writing_value: 'Tone and character.' },
  { word: 'boastful', level: 2, category: 'Character', chinese: '爱吹嘘的', definition: 'Talking with too much pride about oneself.', synonyms: ['bragging', 'conceited'], antonyms: ['modest', 'humble'], word_family: { verb: 'boast', noun: 'boast' }, collocations: ['boastful remark', 'boastful tone'], example_sentence: 'His boastful story left out the teammate who had actually scored.', edutest_frequency: 2, writing_value: 'Voice in dialogue.' },
  { word: 'compassionate', level: 2, category: 'Character', chinese: '有同情心的', definition: 'Feeling and showing concern for another person’s suffering.', synonyms: ['kind', 'empathetic'], antonyms: ['callous', 'heartless'], word_family: { noun: 'compassion', adverb: 'compassionately' }, collocations: ['compassionate response', 'compassionate friend'], example_sentence: 'A compassionate response does not require agreeing with every excuse.', edutest_frequency: 4, writing_value: 'High-value character word.' },
  { word: 'conceited', level: 2, category: 'Character', chinese: '自负的', definition: 'Too proud of one’s own abilities or appearance.', synonyms: ['vain', 'smug'], antonyms: ['modest', 'humble'], word_family: { noun: 'conceit' }, collocations: ['conceited attitude', 'sound conceited'], example_sentence: 'He did not mean to sound conceited, but "obviously" did the damage.', edutest_frequency: 2, writing_value: 'Sharper than "proud".' },
  { word: 'confident', level: 2, category: 'Emotion', chinese: '自信的', definition: 'Sure of one’s own ability, or sure that something is true.', synonyms: ['assured', 'certain'], antonyms: ['insecure', 'doubtful'], word_family: { noun: 'confidence', adverb: 'confidently' }, collocations: ['confident answer', 'grow confident'], example_sentence: 'She wrote a confident opening, then returned to check it was also accurate.', edutest_frequency: 4, writing_value: 'Balance with humility.' },
  { word: 'considerate', level: 2, category: 'Character', chinese: '体贴的', definition: 'Careful not to cause inconvenience or hurt to others.', synonyms: ['thoughtful', 'attentive'], antonyms: ['inconsiderate', 'selfish'], word_family: { noun: 'consideration' }, collocations: ['considerate gesture', 'considerate of'], example_sentence: 'It was considerate to save a seat, and braver to tell the late student the instructions.', edutest_frequency: 3, writing_value: 'Positive social trait.' },
  { word: 'content', level: 2, category: 'Emotion', chinese: '满足的', definition: 'Quietly satisfied with what one has.', synonyms: ['satisfied', 'at ease'], antonyms: ['restless', 'discontented'], word_family: { noun: 'contentment', adverb: 'contentedly' }, collocations: ['content with', 'quietly content'], example_sentence: 'He was content with a solid mark because he knew the work had been honest.', edutest_frequency: 3, writing_value: 'Quieter than "happy".' },
  { word: 'deceitful', level: 2, category: 'Character', chinese: '欺诈的', definition: 'Deliberately hiding the truth or misleading others.', synonyms: ['dishonest', 'duplicitous'], antonyms: ['honest', 'straightforward'], word_family: { noun: 'deceit', verb: 'deceive' }, collocations: ['deceitful smile', 'deceitful claim'], example_sentence: 'The deceitful excuse lasted until someone checked the attendance list.', edutest_frequency: 3, writing_value: 'Moral judgement in narrative.' },
  { word: 'defiant', level: 2, category: 'Character', chinese: '反抗的', definition: 'Openly refusing to obey or give in.', synonyms: ['rebellious', 'resistant'], antonyms: ['obedient', 'submissive'], word_family: { noun: 'defiance', adverb: 'defiantly' }, collocations: ['defiant look', 'defiant silence'], example_sentence: 'Her defiant silence said she would not apologise for a rule she thought unfair.', edutest_frequency: 4, writing_value: 'Conflict and theme.' },
  { word: 'delighted', level: 2, category: 'Emotion', chinese: '欣喜的', definition: 'Very pleased or happy.', synonyms: ['thrilled', 'overjoyed'], antonyms: ['disappointed', 'dismayed'], word_family: { noun: 'delight', adjective: 'delightful' }, collocations: ['delighted to', 'visibly delighted'], example_sentence: 'He was delighted, but he kept the grin small until the results were confirmed.', edutest_frequency: 2, writing_value: 'Controlled joy.' },
  { word: 'desperate', level: 2, category: 'Emotion', chinese: '绝望的', definition: 'Feeling that a situation is so bad that any action might be worth trying.', synonyms: ['frantic', 'despairing'], antonyms: ['calm', 'composed'], word_family: { noun: 'desperation', adverb: 'desperately' }, collocations: ['desperate attempt', 'desperate for'], example_sentence: 'A desperate guess at the last question is still a guess.', edutest_frequency: 4, writing_value: 'Raises stakes.' },
  { word: 'devoted', level: 2, category: 'Character', chinese: '忠诚的', definition: 'Giving a great deal of time, loyalty, or love to someone or something.', synonyms: ['loyal', 'dedicated'], antonyms: ['indifferent', 'disloyal'], word_family: { noun: 'devotion', verb: 'devote' }, collocations: ['devoted friend', 'devoted to'], example_sentence: 'She was devoted to the team, which is why the unfair selection stung.', edutest_frequency: 3, writing_value: 'Loyalty without sentimentality.' },
  { word: 'disappointed', level: 2, category: 'Emotion', chinese: '失望的', definition: 'Sad because something was not as good as hoped.', synonyms: ['let down', 'dismayed'], antonyms: ['satisfied', 'pleased'], word_family: { noun: 'disappointment', verb: 'disappoint' }, collocations: ['disappointed in', 'deeply disappointed'], example_sentence: 'He was disappointed in the mark, and more disappointed in the rushed last page.', edutest_frequency: 3, writing_value: 'Common, but pair with cause.' },
  { word: 'embarrassed', level: 2, category: 'Emotion', chinese: '尴尬的', definition: 'Feeling awkward or ashamed in front of others.', synonyms: ['self-conscious', 'flustered'], antonyms: ['composed', 'unashamed'], word_family: { noun: 'embarrassment', verb: 'embarrass' }, collocations: ['embarrassed silence', 'acutely embarrassed'], example_sentence: 'He felt embarrassed when his stomach answered the silent exam hall.', edutest_frequency: 3, writing_value: 'Social realism.' },
  { word: 'envious', level: 2, category: 'Emotion', chinese: '嫉妒的', definition: 'Wanting what another person has.', synonyms: ['jealous', 'covetous'], antonyms: ['content', 'generous'], word_family: { noun: 'envy', verb: 'envy' }, collocations: ['envious of', 'envious glance'], example_sentence: 'An envious glance at a classmate’s certificate does not write your own.', edutest_frequency: 3, writing_value: 'Distinguish from jealous if possible.' },
  { word: 'faithful', level: 2, category: 'Character', chinese: '忠实的', definition: 'Loyal and reliable; true to a person, duty, or idea.', synonyms: ['loyal', 'steadfast'], antonyms: ['unfaithful', 'fickle'], word_family: { noun: 'faith', adverb: 'faithfully' }, collocations: ['faithful friend', 'faithful account'], example_sentence: 'A faithful account of the argument included the part that made his side look weaker.', edutest_frequency: 3, writing_value: 'Loyalty and accuracy.' },
  { word: 'fierce', level: 2, category: 'Character', chinese: '凶猛的；强烈的', definition: 'Intense, forceful, or showing strong feeling.', synonyms: ['intense', 'ferocious'], antonyms: ['gentle', 'mild'], word_family: { noun: 'fierceness', adverb: 'fiercely' }, collocations: ['fierce competition', 'fierce loyalty'], example_sentence: 'Fierce competition can sharpen a student or merely make him cruel.', edutest_frequency: 3, writing_value: 'Energy in description.' },
  { word: 'forgive', level: 2, category: 'Character', chinese: '原谅', definition: 'To stop blaming someone for an offence.', synonyms: ['pardon', 'excuse'], antonyms: ['resent', 'blame'], word_family: { noun: 'forgiveness', adjective: 'forgiving' }, collocations: ['forgive a mistake', 'hard to forgive'], example_sentence: 'He could forgive the error; he could not ignore the lie that followed it.', edutest_frequency: 3, writing_value: 'Resolution scenes.' },
  { word: 'furious', level: 2, category: 'Emotion', chinese: '狂怒的', definition: 'Extremely angry.', synonyms: ['enraged', 'livid'], antonyms: ['calm', 'placid'], word_family: { noun: 'fury', adverb: 'furiously' }, collocations: ['furious at', 'furious storm'], example_sentence: 'He was furious, which was exactly when he needed to write nothing.', edutest_frequency: 3, writing_value: 'Stronger than "angry".' },
  { word: 'grateful', level: 2, category: 'Emotion', chinese: '感激的', definition: 'Feeling thankful for help or a kindness.', synonyms: ['thankful', 'appreciative'], antonyms: ['ungrateful', 'resentful'], word_family: { noun: 'gratitude', adverb: 'gratefully' }, collocations: ['grateful for', 'deeply grateful'], example_sentence: 'He was grateful for the extra minute, and he used it to reread, not to panic.', edutest_frequency: 3, writing_value: 'Mature emotional register.' },
  { word: 'greedy', level: 2, category: 'Character', chinese: '贪婪的', definition: 'Wanting more than is fair or needed.', synonyms: ['grasping', 'avaricious'], antonyms: ['generous', 'moderate'], word_family: { noun: 'greed', adverb: 'greedily' }, collocations: ['greedy for', 'greedy grab'], example_sentence: 'A greedy grab at every leadership role left the quieter students with none.', edutest_frequency: 2, writing_value: 'Moral critique.' },
  { word: 'hesitant', level: 2, category: 'Emotion', chinese: '犹豫的', definition: 'Slow to act or speak because of uncertainty.', synonyms: ['uncertain', 'wavering'], antonyms: ['decisive', 'assured'], word_family: { noun: 'hesitation', verb: 'hesitate' }, collocations: ['hesitant voice', 'hesitant to'], example_sentence: 'A hesitant answer can still be the correct one if the thinking is sound.', edutest_frequency: 4, writing_value: 'Pairs with reluctant.' },
  { word: 'humble', level: 2, category: 'Character', chinese: '谦逊的', definition: 'Not proud or boastful; modest about ability or status.', synonyms: ['modest', 'unassuming'], antonyms: ['arrogant', 'proud'], word_family: { noun: 'humility', adverb: 'humbly' }, collocations: ['humble apology', 'remain humble'], example_sentence: 'A humble winner names the people who made the result possible.', edutest_frequency: 4, writing_value: 'Scholarship interview gold.' },
  { word: 'impatient', level: 2, category: 'Character', chinese: '不耐烦的', definition: 'Unwilling to wait; easily irritated by delay.', synonyms: ['restless', 'hasty'], antonyms: ['patient', 'tolerant'], word_family: { noun: 'impatience', adverb: 'impatiently' }, collocations: ['impatient sigh', 'impatient with'], example_sentence: 'An impatient sigh in a group task tells everyone who thinks he is the smartest.', edutest_frequency: 3, writing_value: 'Social friction.' },
  { word: 'impulsive', level: 2, category: 'Character', chinese: '冲动的', definition: 'Acting suddenly, without enough thought.', synonyms: ['rash', 'spontaneous'], antonyms: ['considered', 'cautious'], word_family: { noun: 'impulse', adverb: 'impulsively' }, collocations: ['impulsive decision', 'impulsive remark'], example_sentence: 'An impulsive remark in the yard followed him into the classroom.', edutest_frequency: 4, writing_value: 'Cause of plot trouble.' },
  { word: 'indifferent', level: 2, category: 'Emotion', chinese: '冷漠的', definition: 'Not interested or concerned; neither for nor against.', synonyms: ['unconcerned', 'apathetic'], antonyms: ['caring', 'interested'], word_family: { noun: 'indifference', adverb: 'indifferently' }, collocations: ['indifferent to', 'indifferent shrug'], example_sentence: 'He looked indifferent, which was a practised way of hiding that he cared too much.', edutest_frequency: 4, writing_value: 'Tone and character mask.' },
  { word: 'insecure', level: 2, category: 'Emotion', chinese: '缺乏安全感的', definition: 'Not confident; uncertain about oneself or a situation.', synonyms: ['uncertain', 'unconfident'], antonyms: ['secure', 'confident'], word_family: { noun: 'insecurity' }, collocations: ['insecure about', 'feel insecure'], example_sentence: 'Feeling insecure about spelling is not a reason to avoid ambitious words forever.', edutest_frequency: 3, writing_value: 'Interior character.' },
  { word: 'irritable', level: 2, category: 'Emotion', chinese: '易怒的', definition: 'Easily annoyed, especially when tired or tense.', synonyms: ['snappy', 'touchy'], antonyms: ['even-tempered', 'calm'], word_family: { noun: 'irritation', verb: 'irritate' }, collocations: ['irritable mood', 'grow irritable'], example_sentence: 'He grew irritable when the same instruction was repeated, which was a warning to himself.', edutest_frequency: 2, writing_value: 'Realistic emotion.' },
  { word: 'jealous', level: 2, category: 'Emotion', chinese: '妒忌的', definition: 'Afraid of losing someone’s attention, or resentful of a rival.', synonyms: ['envious', 'possessive'], antonyms: ['trusting', 'content'], word_family: { noun: 'jealousy', adverb: 'jealously' }, collocations: ['jealous of', 'jealous streak'], example_sentence: 'Jealous thoughts about a friend’s scholarship offer were less useful than asking how she had prepared.', edutest_frequency: 3, writing_value: 'Relationship conflict.' },
  { word: 'loyal', level: 2, category: 'Character', chinese: '忠诚的', definition: 'Firm in support of a person, group, or idea.', synonyms: ['faithful', 'staunch'], antonyms: ['disloyal', 'treacherous'], word_family: { noun: 'loyalty', adverb: 'loyally' }, collocations: ['loyal friend', 'loyal support'], example_sentence: 'Loyal friendship does not require pretending a bad idea is brilliant.', edutest_frequency: 3, writing_value: 'Theme word.' },
  { word: 'malicious', level: 2, category: 'Character', chinese: '恶意的', definition: 'Intending to hurt or upset someone.', synonyms: ['spiteful', 'cruel'], antonyms: ['kind', 'benevolent'], word_family: { noun: 'malice', adverb: 'maliciously' }, collocations: ['malicious rumour', 'malicious grin'], example_sentence: 'A malicious rumour travels faster than a correction.', edutest_frequency: 3, writing_value: 'Strong moral word; do not overuse.' },
  { word: 'melancholy', level: 2, category: 'Emotion', chinese: '忧郁的', definition: 'A deep, quiet sadness, often without a single simple cause.', synonyms: ['sorrowful', 'pensive'], antonyms: ['cheerful', 'joyful'], word_family: {}, collocations: ['melancholy mood', 'trace of melancholy'], example_sentence: 'A trace of melancholy sat under the joke, and the best readers noticed it.', edutest_frequency: 3, writing_value: 'Literary tone word.' },
  { word: 'mischievous', level: 2, category: 'Character', chinese: '淘气的', definition: 'Playfully causing trouble, usually without serious harm.', synonyms: ['naughty', 'impish'], antonyms: ['well-behaved', 'solemn'], word_family: { noun: 'mischief', adverb: 'mischievously' }, collocations: ['mischievous grin', 'mischievous plan'], example_sentence: 'The mischievous plan to swap name cards lasted until the oral list was printed.', edutest_frequency: 2, writing_value: 'Lighter character colour.' },
  { word: 'modest', level: 2, category: 'Character', chinese: '谦虚的', definition: 'Not talking about one’s abilities; moderate rather than showy.', synonyms: ['humble', 'unpretentious'], antonyms: ['boastful', 'vain'], word_family: { noun: 'modesty', adverb: 'modestly' }, collocations: ['modest claim', 'modest success'], example_sentence: 'A modest claim is easier to defend than a grand one.', edutest_frequency: 4, writing_value: 'Academic tone.' },
  { word: 'obedient', level: 2, category: 'Character', chinese: '顺从的', definition: 'Willing to follow rules or instructions.', synonyms: ['compliant', 'dutiful'], antonyms: ['disobedient', 'defiant'], word_family: { noun: 'obedience', verb: 'obey' }, collocations: ['obedient student', 'obedient to'], example_sentence: 'Obedient students still need to notice when a rule is being used unfairly.', edutest_frequency: 2, writing_value: 'Can be praise or criticism.' },
  { word: 'optimistic', level: 2, category: 'Emotion', chinese: '乐观的', definition: 'Expecting good outcomes; hopeful about the future.', synonyms: ['hopeful', 'upbeat'], antonyms: ['pessimistic', 'gloomy'], word_family: { noun: 'optimism', adverb: 'optimistically' }, collocations: ['optimistic view', 'cautiously optimistic'], example_sentence: 'He stayed cautiously optimistic after the first hard paper.', edutest_frequency: 4, writing_value: 'Perspective word.' },
  { word: 'passionate', level: 2, category: 'Emotion', chinese: '热情的', definition: 'Showing strong feeling or commitment.', synonyms: ['fervent', 'enthusiastic'], antonyms: ['apathetic', 'cool'], word_family: { noun: 'passion', adverb: 'passionately' }, collocations: ['passionate about', 'passionate speech'], example_sentence: 'A passionate speech still needs a structure, or it becomes noise.', edutest_frequency: 3, writing_value: 'Energy with a warning.' },
  { word: 'pessimistic', level: 2, category: 'Emotion', chinese: '悲观的', definition: 'Expecting the worst; seeing difficulties more clearly than hope.', synonyms: ['gloomy', 'negative'], antonyms: ['optimistic', 'hopeful'], word_family: { noun: 'pessimism' }, collocations: ['pessimistic view', 'overly pessimistic'], example_sentence: 'A pessimistic reading of the story missed the small kindness in the last line.', edutest_frequency: 3, writing_value: 'Contrast with optimistic.' },
  { word: 'proud', level: 2, category: 'Emotion', chinese: '骄傲的', definition: 'Pleased with an achievement, or having too high an opinion of oneself.', synonyms: ['pleased', 'dignified'], antonyms: ['ashamed', 'humble'], word_family: { noun: 'pride', adverb: 'proudly' }, collocations: ['proud of', 'too proud'], example_sentence: 'He was proud of the draft and therefore almost refused to improve it.', edutest_frequency: 3, writing_value: 'Two-edged word.' },
  { word: 'rebellious', level: 2, category: 'Character', chinese: '叛逆的', definition: 'Resisting control, custom, or authority.', synonyms: ['defiant', 'unruly'], antonyms: ['obedient', 'compliant'], word_family: { noun: 'rebellion', verb: 'rebel' }, collocations: ['rebellious streak', 'rebellious act'], example_sentence: 'A rebellious streak can be intelligence wearing a louder jacket.', edutest_frequency: 3, writing_value: 'Character complexity.' },
  { word: 'reluctant', level: 2, category: 'Emotion', chinese: '不情愿的', definition: 'Not willing or eager to do something.', synonyms: ['unwilling', 'hesitant'], antonyms: ['eager', 'willing'], word_family: { noun: 'reluctance', adverb: 'reluctantly' }, collocations: ['reluctant to admit', 'reluctant decision'], example_sentence: 'Tom was reluctant to leave his family behind.', edutest_frequency: 5, writing_value: 'Useful for character description.' },
  { word: 'resentful', level: 2, category: 'Emotion', chinese: '愤懑的', definition: 'Feeling bitter because of unfair treatment.', synonyms: ['bitter', 'indignant'], antonyms: ['forgiving', 'content'], word_family: { noun: 'resentment', verb: 'resent' }, collocations: ['resentful of', 'quietly resentful'], example_sentence: 'He felt resentful that effort had been praised less than natural speed.', edutest_frequency: 3, writing_value: 'Interior conflict.' },
  { word: 'respectful', level: 2, category: 'Character', chinese: '恭敬的', definition: 'Showing regard for people, rules, or serious situations.', synonyms: ['courteous', 'polite'], antonyms: ['rude', 'disrespectful'], word_family: { noun: 'respect', verb: 'respect' }, collocations: ['respectful silence', 'respectful disagreement'], example_sentence: 'Respectful disagreement is still disagreement, and it can be the honest kind.', edutest_frequency: 3, writing_value: 'School and interview register.' },
  { word: 'selfish', level: 2, category: 'Character', chinese: '自私的', definition: 'Caring chiefly for oneself and not for others.', synonyms: ['self-centred', 'inconsiderate'], antonyms: ['generous', 'selfless'], word_family: { noun: 'selfishness', adverb: 'selfishly' }, collocations: ['selfish choice', 'selfish motive'], example_sentence: 'The selfish choice was easier, which is why it needed a name.', edutest_frequency: 3, writing_value: 'Clear moral word.' },
  { word: 'sincere', level: 2, category: 'Character', chinese: '真诚的', definition: 'Genuine; not pretended or performed.', synonyms: ['genuine', 'earnest'], antonyms: ['insincere', 'false'], word_family: { noun: 'sincerity', adverb: 'sincerely' }, collocations: ['sincere apology', 'sincere effort'], example_sentence: 'A sincere apology names the harm, not the excuse.', edutest_frequency: 4, writing_value: 'Trust and voice.' },
  { word: 'solemn', level: 2, category: 'Emotion', chinese: '庄严的', definition: 'Serious, formal, and without playfulness.', synonyms: ['grave', 'earnest'], antonyms: ['cheerful', 'light-hearted'], word_family: { noun: 'solemnity', adverb: 'solemnly' }, collocations: ['solemn promise', 'solemn occasion'], example_sentence: 'The hall took on a solemn quiet when the sealed papers arrived.', edutest_frequency: 4, writing_value: 'Atmosphere.' },
  { word: 'stubborn', level: 2, category: 'Character', chinese: '固执的', definition: 'Unwilling to change one’s mind or course.', synonyms: ['obstinate', 'headstrong'], antonyms: ['flexible', 'yielding'], word_family: { noun: 'stubbornness', adverb: 'stubbornly' }, collocations: ['stubborn refusal', 'stubborn streak'], example_sentence: 'Stubborn persistence helped the revision; stubborn pride delayed it.', edutest_frequency: 3, writing_value: 'Two-sided trait.' },
  { word: 'sympathetic', level: 2, category: 'Emotion', chinese: '同情的', definition: 'Understanding and sharing another person’s feelings.', synonyms: ['understanding', 'compassionate'], antonyms: ['unsympathetic', 'harsh'], word_family: { noun: 'sympathy', verb: 'sympathise' }, collocations: ['sympathetic listener', 'sympathetic to'], example_sentence: 'A sympathetic reading of the villain still has to notice the harm.', edutest_frequency: 4, writing_value: 'Reader-response word.' },
  { word: 'timid', level: 2, category: 'Character', chinese: '胆怯的', definition: 'Easily frightened; lacking confidence in company or action.', synonyms: ['shy', 'fearful'], antonyms: ['bold', 'confident'], word_family: { noun: 'timidity', adverb: 'timidly' }, collocations: ['timid voice', 'timid approach'], example_sentence: 'A timid voice can still ask the question that changes the lesson.', edutest_frequency: 3, writing_value: 'Character contrast.' },
  { word: 'vain', level: 2, category: 'Character', chinese: '虚荣的', definition: 'Too concerned with appearance or praise; also, unsuccessful.', synonyms: ['conceited', 'futile'], antonyms: ['modest', 'successful'], word_family: { noun: 'vanity', adverb: 'vainly' }, collocations: ['vain attempt', 'vain about'], example_sentence: 'It was a vain attempt to impress the selector with borrowed phrases.', edutest_frequency: 3, writing_value: 'Two meanings — exam favourite.' },
  { word: 'vengeful', level: 2, category: 'Character', chinese: '报复的', definition: 'Wanting to harm someone in return for a wrong.', synonyms: ['vindictive', 'revengeful'], antonyms: ['forgiving', 'merciful'], word_family: { noun: 'vengeance' }, collocations: ['vengeful act', 'vengeful thought'], example_sentence: 'A vengeful plan made him feel powerful for a minute and smaller afterwards.', edutest_frequency: 2, writing_value: 'Dark motive.' },
  { word: 'vulnerable', level: 2, category: 'Emotion', chinese: '脆弱的', definition: 'Open to being hurt, physically or emotionally.', synonyms: ['exposed', 'defenceless'], antonyms: ['protected', 'secure'], word_family: { noun: 'vulnerability' }, collocations: ['vulnerable to', 'feel vulnerable'], example_sentence: 'He felt vulnerable standing at the front, which is why the first sentence had to be ready.', edutest_frequency: 4, writing_value: 'Mature emotional vocabulary.' },
  { word: 'weary', level: 2, category: 'Emotion', chinese: '疲倦的', definition: 'Very tired, often after long effort or worry.', synonyms: ['exhausted', 'fatigued'], antonyms: ['fresh', 'energetic'], word_family: { noun: 'weariness', verb: 'weary' }, collocations: ['weary sigh', 'grow weary'], example_sentence: 'The weary group still finished the last kilometre without complaint.', edutest_frequency: 3, writing_value: 'Literary tiredness.' },
  { word: 'witty', level: 2, category: 'Character', chinese: '机智的', definition: 'Clever and amusing with words.', synonyms: ['sharp', 'humorous'], antonyms: ['dull', 'humourless'], word_family: { noun: 'wit', adverb: 'wittily' }, collocations: ['witty remark', 'witty reply'], example_sentence: 'A witty remark can rescue a tense room or wound the wrong person.', edutest_frequency: 3, writing_value: 'Voice and dialogue.' },
];
