"""Level 2 Academic Core expansion lemmas. Unique headwords only."""

L2_ROWS: list[tuple[str, str, str]] = [
    ("acknowledge", "verb", "Academic"),
    ("advocate", "verb", "Argument"),
    ("anticipate", "verb", "Academic"),
    ("articulate", "verb", "Argument"),
    ("ascertain", "verb", "Academic"),
    ("assert", "verb", "Argument"),
    ("attain", "verb", "Academic"),
    ("attribute", "verb", "Academic"),
    ("compile", "verb", "Academic"),  # may duplicate L1
    ("complement", "verb", "Academic"),
    ("comprise", "verb", "Academic"),
    ("conceive", "verb", "Academic"),
    ("condemn", "verb", "Argument"),
    ("confine", "verb", "HASS"),
    ("consent", "verb", "HASS"),
    ("contemplate", "verb", "Literary"),
    ("contradict", "verb", "Argument"),
    ("cultivate", "verb", "HASS"),
    ("dedicate", "verb", "Literary"),
    ("deviate", "verb", "Science"),
    ("devote", "verb", "Literary"),
    ("differentiate", "verb", "Academic"),
    ("disclose", "verb", "HASS"),
    ("displace", "verb", "HASS"),
    ("disrupt", "verb", "Science"),
    ("dominate", "verb", "HASS"),
    ("elaborate", "verb", "Academic"),  # Batch 1
    ("embody", "verb", "Literary"),
    ("empower", "verb", "HASS"),
    ("enact", "verb", "HASS"),
    ("encompass", "verb", "Academic"),
    ("endorse", "verb", "Argument"),
    ("enforce", "verb", "HASS"),
    ("enhance", "verb", "Academic"),
    ("enrich", "verb", "Literary"),
    ("entitle", "verb", "HASS"),
    ("envisage", "verb", "Academic"),
    ("evoke", "verb", "Literary"),
    ("exceed", "verb", "Science"),
    ("exhibit", "verb", "Science"),
    ("exploit", "verb", "HASS"),
    ("expose", "verb", "Science"),
    ("facilitate", "verb", "Academic"),
    ("fluctuate", "verb", "Science"),
    ("formulate", "verb", "Academic"),  # Batch 1
    ("foster", "verb", "HASS"),
    ("hinder", "verb", "Academic"),
    ("illuminate", "verb", "Literary"),
    ("implement", "verb", "Academic"),
    ("impose", "verb", "HASS"),
    ("incline", "verb", "Academic"),
    ("incorporate", "verb", "Academic"),
    ("induce", "verb", "Science"),
    ("inhibit", "verb", "Science"),
    ("initiate", "verb", "Academic"),
    ("innovate", "verb", "Science"),
    ("insert", "verb", "Academic"),
    ("inspect", "verb", "Science"),  # L1
    ("institute", "verb", "HASS"),
    ("interact", "verb", "Science"),
    ("intervene", "verb", "HASS"),
    ("justify", "verb", "Argument"),  # Batch 1
    ("manipulate", "verb", "Science"),
    ("mediate", "verb", "HASS"),
    ("mitigate", "verb", "Science"),
    ("negotiate", "verb", "HASS"),
    ("notify", "verb", "Academic"),
    ("offset", "verb", "Science"),
    ("outweigh", "verb", "Argument"),
    ("perceive", "verb", "Literary"),
    ("persist", "verb", "Science"),
    ("portray", "verb", "Literary"),
    ("postpone", "verb", "Academic"),
    ("precede", "verb", "Academic"),
    ("predict", "verb", "Science"),  # Batch 1
    ("prescribe", "verb", "HASS"),
    ("prevail", "verb", "HASS"),
    ("prohibit", "verb", "HASS"),
    ("prompt", "verb", "Academic"),
    ("provoke", "verb", "Literary"),
    ("qualify", "verb", "Academic"),
    ("quantify", "verb", "Science"),
    ("reconcile", "verb", "HASS"),
    ("reconstruct", "verb", "HASS"),
    ("reconsider", "verb", "Academic"),
    ("regulate", "verb", "HASS"),
    ("reiterate", "verb", "Argument"),
    ("relinquish", "verb", "HASS"),
    ("render", "verb", "Literary"),
    ("replicate", "verb", "Science"),
    ("resemble", "verb", "Science"),
    ("resume", "verb", "Academic"),
    ("retain", "verb", "Academic"),  # L1
    ("retrieve", "verb", "Academic"),
    ("reveal", "verb", "Literary"),  # Batch 1
    ("revise", "verb", "Literary"),  # L1
    ("sacrifice", "verb", "Literary"),
    ("scrutinise", "verb", "Academic"),
    ("simulate", "verb", "Science"),
    ("specify", "verb", "Academic"),  # L1
    ("stimulate", "verb", "Science"),
    ("strengthen", "verb", "Argument"),  # L1
    ("submit", "verb", "Academic"),
    ("substitute", "verb", "Science"),
    ("succeed", "verb", "Academic"),  # L1
    ("summarise", "verb", "Academic"),  # Batch 1
    ("supplement", "verb", "Academic"),
    ("suppress", "verb", "HASS"),
    ("surpass", "verb", "Academic"),
    ("suspend", "verb", "HASS"),
    ("sustain", "verb", "Science"),  # L1
    ("terminate", "verb", "Academic"),
    ("testify", "verb", "HASS"),
    ("transcend", "verb", "Literary"),
    ("transmit", "verb", "Science"),
    ("undermine", "verb", "Argument"),
    ("unify", "verb", "HASS"),
    ("utilise", "verb", "Academic"),
    ("validate", "verb", "Science"),  # derivative
    ("withstand", "verb", "Science"),
    ("yield", "verb", "Science"),
    # L2 nouns
    ("abstract", "noun", "Academic"),
    ("adaptation", "noun", "Science"),
    ("agency", "noun", "HASS"),
    ("allegiance", "noun", "HASS"),
    ("alliance", "noun", "HASS"),
    ("allusion", "noun", "Literary"),
    ("analogy", "noun", "Academic"),
    ("anomaly", "noun", "Science"),
    ("anthology", "noun", "Literary"),
    ("appendix", "noun", "Academic"),
    ("architecture", "noun", "HASS"),
    ("archive", "noun", "HASS"),
    ("article", "noun", "Academic"),
    ("aspiration", "noun", "Literary"),
    ("assertion", "noun", "Argument"),
    ("asset", "noun", "HASS"),
    ("assumption", "noun", "Academic"),  # derivative
    ("attitude", "noun", "Literary"),
    ("attribute", "noun", "Academic"),
    ("audit", "noun", "HASS"),
    ("autonomy", "noun", "HASS"),
    ("benchmark", "noun", "Academic"),
    ("biodiversity", "noun", "Science"),
    ("biography", "noun", "Literary"),
    ("bureaucracy", "noun", "HASS"),
    ("capability", "noun", "Academic"),
    ("catalyst", "noun", "Science"),
    ("census", "noun", "HASS"),
    ("chronicle", "noun", "HASS"),
    ("citation", "noun", "Academic"),  # derivative
    ("civilisation", "noun", "HASS"),
    ("classification", "noun", "Science"),
    ("clause", "noun", "HASS"),
    ("coalition", "noun", "HASS"),
    ("code", "noun", "HASS"),
    ("coherence", "noun", "Literary"),  # derivative
    ("collaboration", "noun", "Academic"),
    ("colleague", "noun", "Academic"),
    ("colonist", "noun", "HASS"),
    ("commentary", "noun", "Literary"),
    ("commission", "noun", "HASS"),
    ("commitment", "noun", "HASS"),
    ("commodity", "noun", "HASS"),
    ("commonwealth", "noun", "HASS"),
    ("communication", "noun", "Academic"),
    ("community", "noun", "HASS"),  # L1
    ("compensation", "noun", "HASS"),
    ("competence", "noun", "Academic"),
    ("complexity", "noun", "Academic"),  # derivative
    ("compliance", "noun", "HASS"),
    ("composition", "noun", "Literary"),
    ("compromise", "noun", "HASS"),
    ("computation", "noun", "Science"),
    ("concept", "noun", "Academic"),  # L1
    ("concession", "noun", "Argument"),
    ("confidence", "noun", "Literary"),
    ("conflict", "noun", "HASS"),  # L1
    ("consensus", "noun", "HASS"),
    ("consequence", "noun", "Academic"),  # Batch 1
    ("conservation", "noun", "Science"),  # L1
    ("consistency", "noun", "Academic"),
    ("constituency", "noun", "HASS"),
    ("constraint", "noun", "Academic"),
    ("construction", "noun", "HASS"),
    ("consultant", "noun", "HASS"),
    ("consumption", "noun", "HASS"),
    ("contamination", "noun", "Science"),
    ("context", "noun", "Academic"),  # Batch 1
    ("continuity", "noun", "HASS"),
    ("contradiction", "noun", "Argument"),
    ("contribution", "noun", "HASS"),  # derivative
    ("controversy", "noun", "HASS"),
    ("convention", "noun", "HASS"),
    ("conviction", "noun", "Argument"),
    ("cooperation", "noun", "HASS"),
    ("coordination", "noun", "Academic"),
    ("correlation", "noun", "Science"),
    ("counterpart", "noun", "HASS"),
    ("credibility", "noun", "Argument"),
    ("crisis", "noun", "HASS"),
    ("criterion", "noun", "Academic"),  # derivative
    ("critique", "noun", "Literary"),
    ("currency", "noun", "HASS"),
    ("curriculum", "noun", "Academic"),
    ("custody", "noun", "HASS"),
    ("database", "noun", "Science"),
    ("deadline", "noun", "Academic"),
    ("debate", "noun", "Argument"),
    ("decade", "noun", "HASS"),  # L1 extra
    ("decline", "noun", "HASS"),
    ("deduction", "noun", "Science"),
    ("deficit", "noun", "HASS"),
    ("delegate", "noun", "HASS"),
    ("democracy", "noun", "HASS"),  # L1
    ("demographic", "noun", "HASS"),
    ("demonstration", "noun", "HASS"),  # derivative
    ("denotation", "noun", "Literary"),
    ("deployment", "noun", "HASS"),
    ("depression", "noun", "HASS"),
    ("derivative", "noun", "Academic"),
    ("destination", "noun", "HASS"),
    ("destruction", "noun", "HASS"),
    ("detection", "noun", "Science"),
    ("deterioration", "noun", "Science"),
    ("deviation", "noun", "Science"),
    ("diagnosis", "noun", "Science"),
    ("diagram", "noun", "Science"),
    ("dialogue", "noun", "Literary"),  # L1
    ("dilemma", "noun", "Argument"),
    ("dimension", "noun", "Science"),
    ("diplomacy", "noun", "HASS"),
    ("directive", "noun", "HASS"),
    ("disability", "noun", "HASS"),
    ("disaster", "noun", "HASS"),
    ("discipline", "noun", "Academic"),
    ("discourse", "noun", "Literary"),
    ("discrepancy", "noun", "Academic"),
    ("discretion", "noun", "HASS"),
    ("discrimination", "noun", "HASS"),
    ("disposition", "noun", "Literary"),
    ("dispute", "noun", "HASS"),
    ("disruption", "noun", "Science"),
    ("dissertation", "noun", "Academic"),
    ("distinction", "noun", "Academic"),  # derivative
    ("distribution", "noun", "HASS"),
    ("diversity", "noun", "HASS"),
    ("doctrine", "noun", "HASS"),
    ("document", "noun", "HASS"),  # L1 extra
    ("domain", "noun", "Academic"),
    ("dominance", "noun", "HASS"),
    ("drought", "noun", "Science"),
    ("duration", "noun", "Science"),
    ("dynasty", "noun", "HASS"),
    ("ecology", "noun", "Science"),
    ("economy", "noun", "HASS"),  # L1
    ("edition", "noun", "Literary"),
    ("efficiency", "noun", "Science"),
    ("elaboration", "noun", "Academic"),  # derivative
    ("election", "noun", "HASS"),  # L1
    ("element", "noun", "Science"),  # L1
    ("elite", "noun", "HASS"),
    ("emphasis", "noun", "Academic"),  # derivative
    ("empire", "noun", "HASS"),  # L1
    ("enclosure", "noun", "HASS"),
    ("encounter", "noun", "Literary"),
    ("endurance", "noun", "Literary"),
    ("enforcement", "noun", "HASS"),
    ("engagement", "noun", "HASS"),
    ("engine", "noun", "Science"),
    ("enquiry", "noun", "Academic"),
    ("enterprise", "noun", "HASS"),
    ("entity", "noun", "Academic"),
    ("environment", "noun", "Science"),  # Batch 1
    ("episode", "noun", "Literary"),
    ("epoch", "noun", "HASS"),
    ("equality", "noun", "HASS"),
    ("equation", "noun", "Science"),  # L1 extra
    ("equilibrium", "noun", "Science"),
    ("equity", "noun", "HASS"),
    ("equivalent", "noun", "Science"),
    ("erosion", "noun", "Science"),
    ("error", "noun", "Science"),  # L1
    ("essay", "noun", "Literary"),
    ("essence", "noun", "Academic"),
    ("estimate", "noun", "Science"),
    ("ethics", "noun", "Argument"),
    ("evaluation", "noun", "Academic"),  # derivative
    ("evidence", "noun", "Academic"),  # Batch 1
    ("evolution", "noun", "Science"),
    ("examination", "noun", "Academic"),
    ("exception", "noun", "Academic"),
    ("excerpt", "noun", "Literary"),
    ("excess", "noun", "Science"),
    ("exchange", "noun", "HASS"),  # L1
    ("exclusion", "noun", "HASS"),
    ("excursion", "noun", "HASS"),
    ("execution", "noun", "Academic"),
    ("exemption", "noun", "HASS"),
    ("exhibition", "noun", "HASS"),
    ("exile", "noun", "HASS"),
    ("existence", "noun", "Academic"),
    ("expansion", "noun", "HASS"),
    ("expectation", "noun", "Academic"),
    ("expedition", "noun", "HASS"),
    ("expenditure", "noun", "HASS"),
    ("expense", "noun", "HASS"),
    ("experiment", "noun", "Science"),  # L1
    ("expertise", "noun", "Academic"),
    ("explanation", "noun", "Academic"),  # L1
    ("exploration", "noun", "HASS"),  # L1
    ("export", "noun", "HASS"),  # L1 extra
    ("exposure", "noun", "Science"),
    ("expression", "noun", "Literary"),
    ("extension", "noun", "Academic"),
    ("extent", "noun", "Academic"),
    ("extract", "noun", "Literary"),
    ("extreme", "noun", "Science"),
    ("facility", "noun", "HASS"),
    ("faction", "noun", "HASS"),
    ("factor", "noun", "Academic"),  # Batch 1
    ("faculty", "noun", "Academic"),
    ("failure", "noun", "Academic"),
    ("fairness", "noun", "HASS"),
    ("famine", "noun", "HASS"),
    ("federation", "noun", "HASS"),  # L1
    ("feedback", "noun", "Academic"),
    ("fiction", "noun", "Literary"),  # L1
    ("fieldwork", "noun", "Science"),
    ("filter", "noun", "Science"),
    ("finance", "noun", "HASS"),
    ("finding", "noun", "Science"),  # L1
    ("flexibility", "noun", "Academic"),
    ("fluctuation", "noun", "Science"),
    ("focus", "noun", "Academic"),  # Batch 1 verb
    ("forecast", "noun", "Science"),
    ("formation", "noun", "Science"),
    ("formula", "noun", "Science"),
    ("forum", "noun", "HASS"),
    ("fossil", "noun", "Science"),  # L1
    ("foundation", "noun", "HASS"),
    ("fraction", "noun", "Science"),
    ("fragment", "noun", "Literary"),
    ("framework", "noun", "Academic"),  # L1 extra
    ("franchise", "noun", "HASS"),
    ("frequency", "noun", "Science"),
    ("frontier", "noun", "HASS"),
    ("function", "noun", "Science"),  # L1
    ("funding", "noun", "HASS"),
    ("gap", "noun", "Academic"),
    ("gauge", "noun", "Science"),
    ("gender", "noun", "HASS"),
    ("generation", "noun", "HASS"),
    ("genre", "noun", "Literary"),  # L1
    ("geography", "noun", "HASS"),
    ("gesture", "noun", "Literary"),
    ("glacier", "noun", "Science"),
    ("glossary", "noun", "Academic"),
    ("governance", "noun", "HASS"),
    ("grade", "noun", "Academic"),
    ("gradient", "noun", "Science"),
    ("grant", "noun", "HASS"),
    ("graph", "noun", "Science"),
    ("gravity", "noun", "Science"),
    ("grid", "noun", "Science"),
    ("guideline", "noun", "Academic"),
    ("habitat", "noun", "Science"),  # L1
    ("hardship", "noun", "HASS"),
    ("harmony", "noun", "Literary"),
    ("hazard", "noun", "Science"),
    ("headline", "noun", "Literary"),
    ("heritage", "noun", "HASS"),  # L1
    ("hierarchy", "noun", "HASS"),
    ("highlight", "noun", "Academic"),
    ("historian", "noun", "HASS"),
    ("horizon", "noun", "Literary"),
    ("hostility", "noun", "HASS"),
    ("household", "noun", "HASS"),
    ("humanity", "noun", "HASS"),
    ("hypothesis", "noun", "Science"),  # Batch 1
    # L2 adjectives
    ("abstract", "adjective", "Academic"),
    ("abundant", "adjective", "Science"),  # L1
    ("accurate", "adjective", "Academic"),  # Batch 1
    ("acute", "adjective", "Science"),
    ("adequate", "adjective", "Academic"),
    ("adjacent", "adjective", "Science"),
    ("adverse", "adjective", "Science"),
    ("aesthetic", "adjective", "Literary"),
    ("aggressive", "adjective", "Literary"),
    ("ambitious", "adjective", "Literary"),
    ("analogous", "adjective", "Academic"),
    ("annual", "adjective", "HASS"),  # L1
    ("anonymous", "adjective", "Literary"),
    ("anxious", "adjective", "Literary"),
    ("apparent", "adjective", "Academic"),  # L1
    ("applicable", "adjective", "Academic"),
    ("apprehensive", "adjective", "Literary"),
    ("arbitrary", "adjective", "Academic"),
    ("arid", "adjective", "Science"),
    ("articulate", "adjective", "Argument"),
    ("artificial", "adjective", "Science"),
    ("artistic", "adjective", "Literary"),
    ("assertive", "adjective", "Argument"),
    ("authentic", "adjective", "Literary"),
    ("automatic", "adjective", "Science"),
    ("autonomous", "adjective", "HASS"),
    ("awkward", "adjective", "Literary"),
    ("barren", "adjective", "Science"),
    ("beneficial", "adjective", "Science"),  # derivative
    ("biased", "adjective", "Argument"),
    ("bleak", "adjective", "Literary"),
    ("blunt", "adjective", "Literary"),
    ("bold", "adjective", "Literary"),
    ("bound", "adjective", "Academic"),
    ("brief", "adjective", "Academic"),  # L1
    ("brittle", "adjective", "Science"),
    ("broad", "adjective", "Academic"),
    ("brutal", "adjective", "HASS"),
    ("capable", "adjective", "Academic"),  # L1
    ("cautious", "adjective", "Literary"),  # L1
    ("chronic", "adjective", "Science"),
    ("civic", "adjective", "HASS"),
    ("civil", "adjective", "HASS"),
    ("classic", "adjective", "Literary"),
    ("clinical", "adjective", "Science"),
    ("coastal", "adjective", "HASS"),  # L1
    ("cognitive", "adjective", "Science"),
    ("coherent", "adjective", "Academic"),  # Batch 1
    ("collective", "adjective", "HASS"),
    ("colonial", "adjective", "HASS"),
    ("commercial", "adjective", "HASS"),
    ("commonplace", "adjective", "Academic"),
    ("compact", "adjective", "Science"),
    ("comparable", "adjective", "Academic"),  # derivative
    ("compassionate", "adjective", "Literary"),
    ("compatible", "adjective", "Science"),
    ("compelling", "adjective", "Argument"),
    ("competent", "adjective", "Academic"),
    ("competitive", "adjective", "HASS"),
    ("complementary", "adjective", "Academic"),
    ("complete", "adjective", "Academic"),
    ("complex", "adjective", "Academic"),  # Batch 1
    ("complicated", "adjective", "Academic"),
    ("composed", "adjective", "Literary"),
    ("comprehensive", "adjective", "Academic"),  # Batch 1
    ("compulsory", "adjective", "HASS"),
    ("conceited", "adjective", "Literary"),
    ("concise", "adjective", "Academic"),
    ("concrete", "adjective", "Academic"),
    ("conditional", "adjective", "Academic"),
    ("confident", "adjective", "Literary"),
    ("confidential", "adjective", "HASS"),
    ("conflicting", "adjective", "Argument"),
    ("conscious", "adjective", "Literary"),
    ("consecutive", "adjective", "Academic"),
    ("consequent", "adjective", "Academic"),
    ("conservative", "adjective", "HASS"),
    ("considerable", "adjective", "Academic"),  # L1
    ("considerate", "adjective", "Literary"),
    ("consistent", "adjective", "Science"),  # L1
    ("constant", "adjective", "Science"),  # L1
    ("constitutional", "adjective", "HASS"),
    ("constructive", "adjective", "Argument"),
    ("contemporary", "adjective", "HASS"),
    ("content", "adjective", "Literary"),
    ("continual", "adjective", "Academic"),
    ("continuous", "adjective", "Science"),
    ("controversial", "adjective", "HASS"),
    ("convenient", "adjective", "Academic"),
    ("conventional", "adjective", "HASS"),
    ("convincing", "adjective", "Argument"),
    ("cooperative", "adjective", "HASS"),
    ("core", "adjective", "Academic"),
    ("corporate", "adjective", "HASS"),
    ("correct", "adjective", "Academic"),
    ("corresponding", "adjective", "Academic"),
    ("costly", "adjective", "HASS"),
    ("counterfeit", "adjective", "HASS"),
    ("courageous", "adjective", "Literary"),
    ("creative", "adjective", "Literary"),
    ("credible", "adjective", "Argument"),  # L1
    ("critical", "adjective", "Argument"),
    ("crucial", "adjective", "Academic"),
    ("crude", "adjective", "Science"),
    ("cruel", "adjective", "Literary"),
    ("cultural", "adjective", "HASS"),  # L1
    ("cumulative", "adjective", "Science"),
    ("cunning", "adjective", "Literary"),
    ("curious", "adjective", "Literary"),
    ("current", "adjective", "HASS"),  # L1
    ("customary", "adjective", "HASS"),
    ("cynical", "adjective", "Literary"),
    ("damp", "adjective", "Science"),
    ("dangerous", "adjective", "Science"),
    ("daring", "adjective", "Literary"),
    ("decisive", "adjective", "Argument"),
    ("decorative", "adjective", "Literary"),
    ("dedicated", "adjective", "Literary"),
    ("deep", "adjective", "Literary"),
    ("defensive", "adjective", "HASS"),
    ("definite", "adjective", "Academic"),  # L1
    ("deliberate", "adjective", "Literary"),
    ("delicate", "adjective", "Literary"),
    ("dense", "adjective", "Science"),
    ("dependent", "adjective", "Science"),
    ("descriptive", "adjective", "Literary"),
    ("desirable", "adjective", "Academic"),
    ("desperate", "adjective", "Literary"),
    ("destructive", "adjective", "Science"),
    ("detailed", "adjective", "Academic"),  # L1
    ("determined", "adjective", "Literary"),  # derivative
    ("detrimental", "adjective", "Science"),
    ("devoted", "adjective", "Literary"),
    ("different", "adjective", "Academic"),
    ("digital", "adjective", "Science"),  # L1
    ("diligent", "adjective", "Academic"),  # L1
    ("diplomatic", "adjective", "HASS"),
    ("direct", "adjective", "Academic"),
    ("disadvantaged", "adjective", "HASS"),
    ("disappointed", "adjective", "Literary"),
    ("disastrous", "adjective", "HASS"),
    ("disciplinary", "adjective", "HASS"),
    ("discrete", "adjective", "Science"),
    ("distant", "adjective", "HASS"),
    ("distinct", "adjective", "Academic"),  # L1
    ("diverse", "adjective", "HASS"),
    ("domestic", "adjective", "HASS"),
    ("dominant", "adjective", "HASS"),
    ("dramatic", "adjective", "Literary"),
    ("drastic", "adjective", "Science"),
    ("dual", "adjective", "Academic"),
    ("due", "adjective", "Academic"),
    ("durable", "adjective", "Science"),
    ("dynamic", "adjective", "Science"),
    ("eager", "adjective", "Literary"),  # L1
    ("early", "adjective", "HASS"),
    ("earnest", "adjective", "Literary"),
    ("eastern", "adjective", "HASS"),
    ("easy", "adjective", "Academic"),
    ("ecological", "adjective", "Science"),
    ("economic", "adjective", "HASS"),  # L1
    ("edible", "adjective", "Science"),
    ("educated", "adjective", "HASS"),
    ("effective", "adjective", "Academic"),  # Batch 1
    ("efficient", "adjective", "Science"),
    ("elaborate", "adjective", "Literary"),  # Batch 1 verb
    ("elastic", "adjective", "Science"),
    ("elective", "adjective", "HASS"),
    ("elegant", "adjective", "Literary"),
    ("eligible", "adjective", "HASS"),
    ("elite", "adjective", "HASS"),
    ("eloquent", "adjective", "Literary"),
    ("elusive", "adjective", "Literary"),
    ("eminent", "adjective", "HASS"),
    ("emotional", "adjective", "Literary"),  # L1
    ("emphatic", "adjective", "Argument"),
    ("empirical", "adjective", "Science"),  # Batch 1
    ("empty", "adjective", "Literary"),
    ("enabling", "adjective", "Academic"),
    ("endless", "adjective", "Literary"),
    ("enduring", "adjective", "Literary"),
    ("energetic", "adjective", "Science"),
    ("enforced", "adjective", "HASS"),
    ("engaged", "adjective", "Academic"),
    ("engaging", "adjective", "Literary"),
    ("enormous", "adjective", "Science"),  # L1
    ("enough", "adjective", "Academic"),
    ("entire", "adjective", "Academic"),
    ("environmental", "adjective", "Science"),  # derivative
    ("equal", "adjective", "Science"),  # L1
    ("equitable", "adjective", "HASS"),
    ("equivalent", "adjective", "Science"),
    ("eroded", "adjective", "Science"),
    ("erratic", "adjective", "Science"),
    ("essential", "adjective", "Academic"),  # Batch 1
    ("established", "adjective", "HASS"),
    ("eternal", "adjective", "Literary"),
    ("ethical", "adjective", "Argument"),  # L1
    ("ethnic", "adjective", "HASS"),
    ("evasive", "adjective", "Literary"),
    ("eventual", "adjective", "Academic"),
    ("everyday", "adjective", "Academic"),
    ("evident", "adjective", "Academic"),  # derivative
    ("evolutionary", "adjective", "Science"),
    ("exact", "adjective", "Science"),  # L1
    ("exaggerated", "adjective", "Literary"),
    ("excellent", "adjective", "Academic"),
    ("exceptional", "adjective", "Academic"),
    ("excessive", "adjective", "Academic"),
    ("exclusive", "adjective", "HASS"),
    ("executive", "adjective", "HASS"),
    ("exemplary", "adjective", "Academic"),
    ("exhausted", "adjective", "Literary"),
    ("exhaustive", "adjective", "Academic"),
    ("existing", "adjective", "Academic"),
    ("exotic", "adjective", "HASS"),
    ("expected", "adjective", "Science"),  # L1
    ("expensive", "adjective", "HASS"),
    ("experienced", "adjective", "Academic"),
    ("experimental", "adjective", "Science"),
    ("expert", "adjective", "Academic"),
    ("explicit", "adjective", "Academic"),
    ("exploratory", "adjective", "Science"),
    ("exposed", "adjective", "Science"),
    ("expressive", "adjective", "Literary"),
    ("exquisite", "adjective", "Literary"),
    ("extensive", "adjective", "Academic"),
    ("external", "adjective", "Science"),
    ("extinct", "adjective", "Science"),
    ("extra", "adjective", "Academic"),
    ("extraordinary", "adjective", "Literary"),
    ("extreme", "adjective", "Science"),  # L1
    ("factual", "adjective", "Academic"),
    ("faint", "adjective", "Literary"),
    ("fair", "adjective", "HASS"),
    ("faithful", "adjective", "Literary"),
    ("false", "adjective", "Argument"),
    ("familiar", "adjective", "Academic"),  # L1
    ("famous", "adjective", "HASS"),
    ("fantastic", "adjective", "Literary"),
    ("far-reaching", "adjective", "HASS"),
    ("fascinating", "adjective", "Literary"),
    ("fashionable", "adjective", "HASS"),
    ("fatal", "adjective", "Science"),
    ("favourable", "adjective", "HASS"),
    ("feasible", "adjective", "Academic"),
    ("federal", "adjective", "HASS"),
    ("feeble", "adjective", "Literary"),
    ("fertile", "adjective", "Science"),
    ("fierce", "adjective", "Literary"),
    ("figurative", "adjective", "Literary"),
    ("final", "adjective", "Academic"),  # L1
    ("financial", "adjective", "HASS"),  # L1
    ("finite", "adjective", "Science"),
    ("firm", "adjective", "Argument"),
    ("first-hand", "adjective", "HASS"),  # L1
    ("flexible", "adjective", "Academic"),
    ("fluent", "adjective", "Literary"),
    ("fluid", "adjective", "Science"),
    ("focused", "adjective", "Academic"),
    ("following", "adjective", "Academic"),
    ("forceful", "adjective", "Argument"),
    ("foreign", "adjective", "HASS"),
    ("formal", "adjective", "Literary"),  # L1
    ("former", "adjective", "HASS"),
    ("forthcoming", "adjective", "Academic"),
    ("fortunate", "adjective", "Literary"),
    ("fossil", "adjective", "Science"),
    ("fragile", "adjective", "Science"),
    ("fragmented", "adjective", "HASS"),
    ("fragrant", "adjective", "Science"),
    ("frail", "adjective", "Literary"),
    ("frank", "adjective", "Literary"),
    ("frantic", "adjective", "Literary"),
    ("frequent", "adjective", "Academic"),  # L1
    ("fresh", "adjective", "Science"),
    ("friendly", "adjective", "Literary"),
    ("frigid", "adjective", "Science"),
    ("fruitful", "adjective", "Academic"),
    ("frustrated", "adjective", "Literary"),
    ("full-scale", "adjective", "HASS"),
    ("functional", "adjective", "Science"),
    ("fundamental", "adjective", "Academic"),
    ("furious", "adjective", "Literary"),
    ("further", "adjective", "Academic"),
    ("futile", "adjective", "Argument"),
    ("future", "adjective", "HASS"),
    # L2 adverbs
    ("accordingly", "adverb", "Academic"),
    ("adequately", "adverb", "Academic"),
    ("apparently", "adverb", "Academic"),
    ("approximately", "adverb", "Science"),
    ("consequently", "adverb", "Academic"),
    ("considerably", "adverb", "Academic"),
    ("consistently", "adverb", "Academic"),
    ("deliberately", "adverb", "Literary"),
    ("effectively", "adverb", "Academic"),  # L1
    ("essentially", "adverb", "Academic"),  # derivative
    ("eventually", "adverb", "Academic"),  # L1
    ("explicitly", "adverb", "Academic"),
    ("formerly", "adverb", "HASS"),
    ("frequently", "adverb", "Academic"),
    ("furthermore", "adverb", "Argument"),
    ("generally", "adverb", "Academic"),  # L1
    ("hence", "adverb", "Academic"),
    ("however", "adverb", "Argument"),
    ("increasingly", "adverb", "Academic"),
    ("indirectly", "adverb", "Academic"),
    ("inevitably", "adverb", "Academic"),
    ("initially", "adverb", "Academic"),
    ("largely", "adverb", "Academic"),
    ("likewise", "adverb", "Academic"),
    ("meanwhile", "adverb", "Literary"),
    ("moreover", "adverb", "Argument"),
    ("namely", "adverb", "Academic"),
    ("nevertheless", "adverb", "Argument"),
    ("nonetheless", "adverb", "Argument"),
    ("notably", "adverb", "Academic"),
    ("partly", "adverb", "Academic"),
    ("precisely", "adverb", "Academic"),
    ("primarily", "adverb", "Academic"),
    ("relatively", "adverb", "Academic"),
    ("respectively", "adverb", "Academic"),
    ("subsequently", "adverb", "Academic"),  # derivative
    ("therefore", "adverb", "Argument"),
    ("thereby", "adverb", "Academic"),
    ("thus", "adverb", "Academic"),
    ("ultimately", "adverb", "Academic"),
    ("undoubtedly", "adverb", "Argument"),
    ("unfortunately", "adverb", "Literary"),
    ("widely", "adverb", "Academic"),
]
